In [1]:
import pandas as pd

In [2]:
import numpy as np

In [120]:
%ls

 El volumen de la unidad C es Local Disk
 El n√∫mero de serie del volumen es: 0671-FAEA

 Directorio de C:\Users\Monica\PROJECTS

01/02/2024  15:39    <DIR>          .
01/02/2024  15:39    <DIR>          ..
29/01/2024  18:40               205 .cache
01/02/2024  09:27    <DIR>          .ipynb_checkpoints
18/01/2024  19:36            13.731 Escape Room_Solution.ipynb
01/02/2024  15:39           589.136 Project Sleep Efficiency.ipynb
01/02/2024  15:37            88.274 s1.csv
30/01/2024  16:37            41.369 Sleep_Efficiency.csv
30/01/2024  13:21            24.072 ss.csv
26/01/2024  09:38           268.198 TIBUS (1) (1).ipynb
26/01/2024  13:38           306.539 TIBUS (2).ipynb
30/01/2024  15:29           507.203 TIBUS (3).ipynb
               9 archivos      1.838.727 bytes
               3 dirs  162.507.022.336 bytes libres

In [4]:
ss = pd.read_csv('ss.csv')
ss.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [5]:
ss.tail()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
368,369,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [6]:
ss.shape

(373, 13)

In [7]:
ss.duplicated().any()

False

In [8]:
ss.columns.str.lower()

Index(['person id', 'gender', 'age', 'occupation', 'sleep duration',
       'quality of sleep', 'physical activity level', 'stress level',
       'bmi category', 'blood pressure', 'heart rate', 'daily steps',
       'sleep disorder'],
      dtype='object')

In [9]:
ss.columns = ss.columns.str.replace(' ', '_')
ss.columns

Index(['Person_ID', 'Gender', 'Age', 'Occupation', 'Sleep_Duration',
       'Quality_of_Sleep', 'Physical_Activity_Level', 'Stress_Level',
       'BMI_Category', 'Blood_Pressure', 'Heart_Rate', 'Daily_Steps',
       'Sleep_Disorder'],
      dtype='object')

In [10]:
ss.columns = ss.columns.str.lower()
ss.columns

Index(['person_id', 'gender', 'age', 'occupation', 'sleep_duration',
       'quality_of_sleep', 'physical_activity_level', 'stress_level',
       'bmi_category', 'blood_pressure', 'heart_rate', 'daily_steps',
       'sleep_disorder'],
      dtype='object')

In [11]:
ss.head()

,person_id,gender,age,occupation,sleep_duration,quality_of_sleep,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [12]:
ss.isna().sum()

person_id                    0
gender                       0
age                          0
occupation                   0
sleep_duration               0
quality_of_sleep             0
physical_activity_level      0
stress_level                 0
bmi_category                 0
blood_pressure               0
heart_rate                   0
daily_steps                  0
sleep_disorder             219
dtype: int64

In [13]:
ss.sleep_disorder = ss.sleep_disorder.fillna('None')

In [14]:
ss.isna().sum()

person_id                  0
gender                     0
age                        0
occupation                 0
sleep_duration             0
quality_of_sleep           0
physical_activity_level    0
stress_level               0
bmi_category               0
blood_pressure             0
heart_rate                 0
daily_steps                0
sleep_disorder             0
dtype: int64

In [15]:
ss

,person_id,gender,age,occupation,sleep_duration,quality_of_sleep,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,369,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [16]:
import pandas as pd

In [17]:
%ls

 El volumen de la unidad C es Local Disk
 El n√∫mero de serie del volumen es: 0671-FAEA

 Directorio de C:\Users\Monica\PROJECTS

01/02/2024  13:41    <DIR>          .
01/02/2024  13:41    <DIR>          ..
29/01/2024  18:40               205 .cache
01/02/2024  09:27    <DIR>          .ipynb_checkpoints
18/01/2024  19:36            13.731 Escape Room_Solution.ipynb
01/02/2024  13:41            43.530 Project Sleep Efficiency.ipynb
30/01/2024  16:37            41.369 Sleep_Efficiency.csv
30/01/2024  13:21            24.072 ss.csv
26/01/2024  09:38           268.198 TIBUS (1) (1).ipynb
26/01/2024  13:38           306.539 TIBUS (2).ipynb
30/01/2024  15:29           507.203 TIBUS (3).ipynb
               8 archivos      1.204.847 bytes
               3 dirs  162.547.249.152 bytes libres

In [18]:
se = pd.read_csv("Sleep_Efficiency.csv")
se

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,448,27,Female,2021-11-13 22:00:00,2021-11-13 05:30:00,7.5,0.91,22,57,21,0.0,0.0,0.0,No,5.0
448,449,52,Male,2021-03-31 21:00:00,2021-03-31 03:00:00,6.0,0.74,28,57,15,4.0,25.0,0.0,No,3.0
449,450,40,Female,2021-09-07 23:00:00,2021-09-07 07:30:00,8.5,0.55,20,32,48,1.0,NaN,3.0,Yes,0.0
450,451,45,Male,2021-07-29 21:00:00,2021-07-29 04:00:00,7.0,0.76,18,72,10,3.0,0.0,0.0,No,3.0
451,452,18,Male,2021-03-17 02:30:00,2021-03-17 10:00:00,7.5,0.63,22,23,55,1.0,50.0,0.0,No,1.0

In [19]:
se.shape

(452, 15)

In [20]:
se.columns.str.lower()

Index(['id', 'age', 'gender', 'bedtime', 'wakeup time', 'sleep duration',
       'sleep efficiency', 'rem sleep percentage', 'deep sleep percentage',
       'light sleep percentage', 'awakenings', 'caffeine consumption',
       'alcohol consumption', 'smoking status', 'exercise frequency'],
      dtype='object')

In [21]:
se.columns = se.columns.str.replace(' ', '_')
se.columns

Index(['ID', 'Age', 'Gender', 'Bedtime', 'Wakeup_time', 'Sleep_duration',
       'Sleep_efficiency', 'REM_sleep_percentage', 'Deep_sleep_percentage',
       'Light_sleep_percentage', 'Awakenings', 'Caffeine_consumption',
       'Alcohol_consumption', 'Smoking_status', 'Exercise_frequency'],
      dtype='object')

In [22]:
se.columns = se.columns.str.lower()
se.columns

Index(['id', 'age', 'gender', 'bedtime', 'wakeup_time', 'sleep_duration',
       'sleep_efficiency', 'rem_sleep_percentage', 'deep_sleep_percentage',
       'light_sleep_percentage', 'awakenings', 'caffeine_consumption',
       'alcohol_consumption', 'smoking_status', 'exercise_frequency'],
      dtype='object')

In [23]:
se.head()

,id,age,gender,bedtime,wakeup_time,sleep_duration,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0

In [24]:
se.tail()

,id,age,gender,bedtime,wakeup_time,sleep_duration,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
447,448,27,Female,2021-11-13 22:00:00,2021-11-13 05:30:00,7.5,0.91,22,57,21,0.0,0.0,0.0,No,5.0
448,449,52,Male,2021-03-31 21:00:00,2021-03-31 03:00:00,6.0,0.74,28,57,15,4.0,25.0,0.0,No,3.0
449,450,40,Female,2021-09-07 23:00:00,2021-09-07 07:30:00,8.5,0.55,20,32,48,1.0,NaN,3.0,Yes,0.0
450,451,45,Male,2021-07-29 21:00:00,2021-07-29 04:00:00,7.0,0.76,18,72,10,3.0,0.0,0.0,No,3.0
451,452,18,Male,2021-03-17 02:30:00,2021-03-17 10:00:00,7.5,0.63,22,23,55,1.0,50.0,0.0,No,1.0

In [25]:
ss.tail()

,person_id,gender,age,occupation,sleep_duration,quality_of_sleep,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
368,369,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [26]:
se.duplicated().any()

False

In [27]:
se.isna().sum()

id                         0
age                        0
gender                     0
bedtime                    0
wakeup_time                0
sleep_duration             0
sleep_efficiency           0
rem_sleep_percentage       0
deep_sleep_percentage      0
light_sleep_percentage     0
awakenings                20
caffeine_consumption      25
alcohol_consumption       14
smoking_status             0
exercise_frequency         6
dtype: int64

In [28]:
se.awakenings.unique()

array([ 0.,  3.,  1.,  2.,  4., nan])

In [29]:
se.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      452 non-null    int64
 1   age                     452 non-null    int64
 2   gender                  452 non-null    object
 3   bedtime                 452 non-null    object
 4   wakeup_time             452 non-null    object
 5   sleep_duration          452 non-null    float64
 6   sleep_efficiency        452 non-null    float64
 7   rem_sleep_percentage    452 non-null    int64
 8   deep_sleep_percentage   452 non-null    int64
 9   light_sleep_percentage  452 non-null    int64
 10  awakenings              432 non-null    float64
 11  caffeine_consumption    427 non-null    float64
 12  alcohol_consumption     438 non-null    float64
 13  smoking_status          452 non-null    object
 14  exercise_frequency      446 non-null    float64
dtypes: float64(6), int64(5), object(4)
memory usage: 53.1+ KB

In [30]:
se.awakenings = se.awakenings.fillna(se.awakenings.mean())

In [31]:
se['awakenings'] = se['awakenings'].apply(lambda x: int(x) if type(x)==float else x)
se['awakenings'].unique()

array([0, 3, 1, 2, 4], dtype=int64)

In [32]:
se.caffeine_consumption.unique()

array([  0.,  50.,  nan,  25.,  75., 200., 100.])

In [33]:
se.caffeine_consumption = se.caffeine_consumption.fillna(se.caffeine_consumption.mean())

In [34]:
se['caffeine_consumption'] = se['caffeine_consumption'].apply(lambda x: int(x) if type(x)==float else x)
se['caffeine_consumption'].unique()

array([  0,  50,  23,  25,  75, 200, 100], dtype=int64)

In [35]:
se.alcohol_consumption.unique()

array([ 0.,  3.,  5.,  1.,  2., nan,  4.])

In [36]:
se.alcohol_consumption = se.alcohol_consumption.fillna(se.alcohol_consumption.mean())

In [37]:
se['alcohol_consumption'] = se['alcohol_consumption'].apply(lambda x: int(x) if type(x)==float else x)
se['alcohol_consumption'].unique()

array([0, 3, 5, 1, 2, 4], dtype=int64)

In [38]:
se.exercise_frequency.unique()

array([ 3.,  1.,  0.,  5.,  2.,  4., nan])

In [39]:
se.exercise_frequency = se.exercise_frequency.fillna(se.exercise_frequency.mean())

In [40]:
se['exercise_frequency'] = se['exercise_frequency'].apply(lambda x: int(x) if type(x)==float else x)
se['exercise_frequency'].unique()

array([3, 1, 0, 5, 2, 4], dtype=int64)

In [41]:
ss['quality_of_sleep'] = ss['quality_of_sleep'].apply(lambda x: float(x) if type(x)==int else x)
ss['quality_of_sleep'].unique()

array([6., 4., 7., 5., 8., 9.])

In [42]:
se.isna().sum()

id                        0
age                       0
gender                    0
bedtime                   0
wakeup_time               0
sleep_duration            0
sleep_efficiency          0
rem_sleep_percentage      0
deep_sleep_percentage     0
light_sleep_percentage    0
awakenings                0
caffeine_consumption      0
alcohol_consumption       0
smoking_status            0
exercise_frequency        0
dtype: int64

In [43]:
ss.isna().sum()

person_id                  0
gender                     0
age                        0
occupation                 0
sleep_duration             0
quality_of_sleep           0
physical_activity_level    0
stress_level               0
bmi_category               0
blood_pressure             0
heart_rate                 0
daily_steps                0
sleep_disorder             0
dtype: int64

In [44]:
ss.info()
se.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 373 entries, 0 to 372
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   person_id                373 non-null    int64
 1   gender                   373 non-null    object
 2   age                      373 non-null    int64
 3   occupation               373 non-null    object
 4   sleep_duration           373 non-null    float64
 5   quality_of_sleep         373 non-null    float64
 6   physical_activity_level  373 non-null    int64
 7   stress_level             373 non-null    int64
 8   bmi_category             373 non-null    object
 9   blood_pressure           373 non-null    object
 10  heart_rate               373 non-null    int64
 11  daily_steps              373 non-null    int64
 12  sleep_disorder           373 non-null    object
dtypes: float64(2), int64(6), object(5)
memory usage: 38.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      452 non-null    int64
 1   age                     452 non-null    int64
 2   gender                  452 non-null    object
 3   bedtime                 452 non-null    object
 4   wakeup_time             452 non-null    object
 5   sleep_duration          452 non-null    float64
 6   sleep_efficiency        452 non-null    float64
 7   rem_sleep_percentage    452 non-null    int64
 8   deep_sleep_percentage   452 non-null    int64
 9   light_sleep_percentage  452 non-null    int64
 10  awakenings              452 non-null    int64
 11  caffeine_consumption    452 non-null    int64
 12  alcohol_consumption     452 non-null    int64
 13  smoking_status          452 non-null    object
 14  exercise_frequency      452 non-null    int64
dtypes: float64(2), int64(9), object(4)
memory usage: 53.1+ KB

In [45]:
se

,id,age,gender,bedtime,wakeup_time,sleep_duration,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0,0,0,Yes,3
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3,0,3,Yes,3
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1,0,0,No,3
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3,50,5,Yes,1
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3,0,3,No,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,448,27,Female,2021-11-13 22:00:00,2021-11-13 05:30:00,7.5,0.91,22,57,21,0,0,0,No,5
448,449,52,Male,2021-03-31 21:00:00,2021-03-31 03:00:00,6.0,0.74,28,57,15,4,25,0,No,3
449,450,40,Female,2021-09-07 23:00:00,2021-09-07 07:30:00,8.5,0.55,20,32,48,1,23,3,Yes,0
450,451,45,Male,2021-07-29 21:00:00,2021-07-29 04:00:00,7.0,0.76,18,72,10,3,0,0,No,3
451,452,18,Male,2021-03-17 02:30:00,2021-03-17 10:00:00,7.5,0.63,22,23,55,1,50,0,No,1

In [46]:
se = se.drop(columns=['bedtime', 'wakeup_time'])

In [47]:
s = pd.concat([ss, se])
s

,person_id,gender,age,occupation,sleep_duration,quality_of_sleep,physical_activity_level,stress_level,bmi_category,blood_pressure,...,id,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,1.0,Male,27,Software Engineer,6.1,6.0,42.0,6.0,Overweight,126/83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Male,28,Doctor,6.2,6.0,60.0,8.0,Normal,125/80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Male,28,Doctor,6.2,6.0,60.0,8.0,Normal,125/80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Male,28,Sales Representative,5.9,4.0,30.0,8.0,Obese,140/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Male,28,Sales Representative,5.9,4.0,30.0,8.0,Obese,140/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,NaN,Female,27,NaN,7.5,NaN,NaN,NaN,NaN,NaN,...,448.0,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5.0
448,NaN,Male,52,NaN,6.0,NaN,NaN,NaN,NaN,NaN,...,449.0,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3.0
449,NaN,Female,40,NaN,8.5,NaN,NaN,NaN,NaN,NaN,...,450.0,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0.0
450,NaN,Male,45,NaN,7.0,NaN,NaN,NaN,NaN,NaN,...,451.0,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3.0
451,NaN,Male,18,NaN,7.5,NaN,NaN,NaN,NaN,NaN,...,452.0,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1.0

In [48]:
s = s.reset_index()
s

,index,person_id,gender,age,occupation,sleep_duration,quality_of_sleep,physical_activity_level,stress_level,bmi_category,...,id,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,0,1.0,Male,27,Software Engineer,6.1,6.0,42.0,6.0,Overweight,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2.0,Male,28,Doctor,6.2,6.0,60.0,8.0,Normal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,3.0,Male,28,Doctor,6.2,6.0,60.0,8.0,Normal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,4.0,Male,28,Sales Representative,5.9,4.0,30.0,8.0,Obese,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,5.0,Male,28,Sales Representative,5.9,4.0,30.0,8.0,Obese,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,447,NaN,Female,27,NaN,7.5,NaN,NaN,NaN,NaN,...,448.0,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5.0
821,448,NaN,Male,52,NaN,6.0,NaN,NaN,NaN,NaN,...,449.0,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3.0
822,449,NaN,Female,40,NaN,8.5,NaN,NaN,NaN,NaN,...,450.0,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0.0
823,450,NaN,Male,45,NaN,7.0,NaN,NaN,NaN,NaN,...,451.0,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3.0
824,451,NaN,Male,18,NaN,7.5,NaN,NaN,NaN,NaN,...,452.0,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1.0

In [49]:
s = s.drop(columns=['person_id', 'id', 'index'])

In [50]:
s.head()

,gender,age,occupation,sleep_duration,quality_of_sleep,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,...,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,42.0,6.0,Overweight,126/83,77.0,...,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Male,28,Doctor,6.2,6.0,60.0,8.0,Normal,125/80,75.0,...,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Male,28,Doctor,6.2,6.0,60.0,8.0,Normal,125/80,75.0,...,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Male,28,Sales Representative,5.9,4.0,30.0,8.0,Obese,140/90,85.0,...,Sleep Apnea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Male,28,Sales Representative,5.9,4.0,30.0,8.0,Obese,140/90,85.0,...,Sleep Apnea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
s.tail()

,gender,age,occupation,sleep_duration,quality_of_sleep,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,...,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
820,Female,27,NaN,7.5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5.0
821,Male,52,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3.0
822,Female,40,NaN,8.5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0.0
823,Male,45,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3.0
824,Male,18,NaN,7.5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1.0

In [52]:
s.isna().sum()

gender                       0
age                          0
occupation                 452
sleep_duration               0
quality_of_sleep           452
physical_activity_level    452
stress_level               452
bmi_category               452
blood_pressure             452
heart_rate                 452
daily_steps                452
sleep_disorder             452
sleep_efficiency           373
rem_sleep_percentage       373
deep_sleep_percentage      373
light_sleep_percentage     373
awakenings                 373
caffeine_consumption       373
alcohol_consumption        373
smoking_status             373
exercise_frequency         373
dtype: int64

In [53]:
s.quality_of_sleep.unique()

array([ 6.,  4.,  7.,  5.,  8.,  9., nan])

In [54]:
se.info()
ss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      452 non-null    int64
 1   age                     452 non-null    int64
 2   gender                  452 non-null    object
 3   sleep_duration          452 non-null    float64
 4   sleep_efficiency        452 non-null    float64
 5   rem_sleep_percentage    452 non-null    int64
 6   deep_sleep_percentage   452 non-null    int64
 7   light_sleep_percentage  452 non-null    int64
 8   awakenings              452 non-null    int64
 9   caffeine_consumption    452 non-null    int64
 10  alcohol_consumption     452 non-null    int64
 11  smoking_status          452 non-null    object
 12  exercise_frequency      452 non-null    int64
dtypes: float64(2), int64(9), object(2)
memory usage: 46.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 373 entries, 0 to 372
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   person_id                373 non-null    int64
 1   gender                   373 non-null    object
 2   age                      373 non-null    int64
 3   occupation               373 non-null    object
 4   sleep_duration           373 non-null    float64
 5   quality_of_sleep         373 non-null    float64
 6   physical_activity_level  373 non-null    int64
 7   stress_level             373 non-null    int64
 8   bmi_category             373 non-null    object
 9   blood_pressure           373 non-null    object
 10  heart_rate               373 non-null    int64
 11  daily_steps              373 non-null    int64
 12  sleep_disorder           373 non-null    object
dtypes: float64(2), int64(6), object(5)
memory usage: 38.0+ KB

In [55]:
import pandas as pd

s_copy = s.copy()

sleep_efficiency_mean = s_copy['sleep_efficiency'].mean()
s_copy['sleep_efficiency'].fillna(sleep_efficiency_mean, inplace=True)


for index, row in s_copy.iterrows():
    if 4.0 <= row['quality_of_sleep'] <= 9.0:
        s_copy.at[index, 'sleep_efficiency'] = (row['quality_of_sleep'] - 4.0) / 5.0 + 0.4


s_copy.drop('quality_of_sleep', axis=1, inplace=True)


print(s_copy)

     gender  age            occupation  sleep_duration  \
0      Male   27     Software Engineer             6.1
1      Male   28                Doctor             6.2
2      Male   28                Doctor             6.2
3      Male   28  Sales Representative             5.9
4      Male   28  Sales Representative             5.9
..      ...  ...                   ...             ...
820  Female   27                   NaN             7.5
821    Male   52                   NaN             6.0
822  Female   40                   NaN             8.5
823    Male   45                   NaN             7.0
824    Male   18                   NaN             7.5

     physical_activity_level  stress_level bmi_category blood_pressure  \
0                       42.0           6.0   Overweight         126/83
1                       60.0           8.0       Normal         125/80
2                       60.0           8.0       Normal         125/80
3                       30.0           8.0        Obese         140/90
4                       30.0           8.0        Obese         140/90
..                       ...           ...          ...            ...
820                      NaN           NaN          NaN            NaN
821                      NaN           NaN          NaN            NaN
822                      NaN           NaN          NaN            NaN
823                      NaN           NaN          NaN            NaN
824                      NaN           NaN          NaN            NaN

     heart_rate  daily_steps sleep_disorder  sleep_efficiency  \
0          77.0       4200.0           None              0.80
1          75.0      10000.0           None              0.80
2          75.0      10000.0           None              0.80
3          85.0       3000.0    Sleep Apnea              0.40
4          85.0       3000.0    Sleep Apnea              0.40
..          ...          ...            ...               ...
820         NaN          NaN            NaN              0.91
821         NaN          NaN            NaN              0.74
822         NaN          NaN            NaN              0.55
823         NaN          NaN            NaN              0.76
824         NaN          NaN            NaN              0.63

     rem_sleep_percentage  deep_sleep_percentage  light_sleep_percentage  \
0                     NaN                    NaN                     NaN
1                     NaN                    NaN                     NaN
2                     NaN                    NaN                     NaN
3                     NaN                    NaN                     NaN
4                     NaN                    NaN                     NaN
..                    ...                    ...                     ...
820                  22.0                   57.0                    21.0
821                  28.0                   57.0                    15.0
822                  20.0                   32.0                    48.0
823                  18.0                   72.0                    10.0
824                  22.0                   23.0                    55.0

     awakenings  caffeine_consumption  alcohol_consumption smoking_status  \
0           NaN                   NaN                  NaN            NaN
1           NaN                   NaN                  NaN            NaN
2           NaN                   NaN                  NaN            NaN
3           NaN                   NaN                  NaN            NaN
4           NaN                   NaN                  NaN            NaN
..          ...                   ...                  ...            ...
820         0.0                   0.0                  0.0             No
821         4.0                  25.0                  0.0             No
822         1.0                  23.0                  3.0            Yes
823         3.0                   0.0                  0.0             No
824         1.0                  50.0                  0.0             No

     exercise_frequency
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
..                  ...
820                 5.0
821                 3.0
822                 0.0
823                 3.0
824                 1.0

[825 rows x 20 columns]

In [56]:
s1 = pd.DataFrame(s_copy)
s1

,gender,age,occupation,sleep_duration,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,42.0,6.0,Overweight,126/83,77.0,4200.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Male,28,Doctor,6.2,60.0,8.0,Normal,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Male,28,Doctor,6.2,60.0,8.0,Normal,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Male,28,Sales Representative,5.9,30.0,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Male,28,Sales Representative,5.9,30.0,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,NaN,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5.0
821,Male,52,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3.0
822,Female,40,NaN,8.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0.0
823,Male,45,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3.0
824,Male,18,NaN,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1.0

In [57]:
s1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   gender                   825 non-null    object
 1   age                      825 non-null    int64
 2   occupation               373 non-null    object
 3   sleep_duration           825 non-null    float64
 4   physical_activity_level  373 non-null    float64
 5   stress_level             373 non-null    float64
 6   bmi_category             373 non-null    object
 7   blood_pressure           373 non-null    object
 8   heart_rate               373 non-null    float64
 9   daily_steps              373 non-null    float64
 10  sleep_disorder           373 non-null    object
 11  sleep_efficiency         825 non-null    float64
 12  rem_sleep_percentage     452 non-null    float64
 13  deep_sleep_percentage    452 non-null    float64
 14  light_sleep_percentage   452 non-null    float64
 15  awakenings               452 non-null    float64
 16  caffeine_consumption     452 non-null    float64
 17  alcohol_consumption      452 non-null    float64
 18  smoking_status           452 non-null    object
 19  exercise_frequency       452 non-null    float64
dtypes: float64(13), int64(1), object(6)
memory usage: 129.0+ KB

In [58]:
import pandas as pd

s1_copy = s1.copy()

s1_copy['exercise_frequency'].fillna(5.0, inplace=True)

s1_copy.drop('physical_activity_level', axis=1, inplace=True)

print(s1_copy)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27                   NaN             7.5           NaN
821    Male   52                   NaN             6.0           NaN
822  Female   40                   NaN             8.5           NaN
823    Male   45                   NaN             7.0           NaN
824    Male   18                   NaN             7.5           NaN

    bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0     Overweight         126/83        77.0       4200.0           None
1         Normal         125/80        75.0      10000.0           None
2         Normal         125/80        75.0      10000.0           None
3          Obese         140/90        85.0       3000.0    Sleep Apnea
4          Obese         140/90        85.0       3000.0    Sleep Apnea
..           ...            ...         ...          ...            ...
820          NaN            NaN         NaN          NaN            NaN
821          NaN            NaN         NaN          NaN            NaN
822          NaN            NaN         NaN          NaN            NaN
823          NaN            NaN         NaN          NaN            NaN
824          NaN            NaN         NaN          NaN            NaN

     sleep_efficiency  rem_sleep_percentage  deep_sleep_percentage  \
0                0.80                   NaN                    NaN
1                0.80                   NaN                    NaN
2                0.80                   NaN                    NaN
3                0.40                   NaN                    NaN
4                0.40                   NaN                    NaN
..                ...                   ...                    ...
820              0.91                  22.0                   57.0
821              0.74                  28.0                   57.0
822              0.55                  20.0                   32.0
823              0.76                  18.0                   72.0
824              0.63                  22.0                   23.0

     light_sleep_percentage  awakenings  caffeine_consumption  \
0                       NaN         NaN                   NaN
1                       NaN         NaN                   NaN
2                       NaN         NaN                   NaN
3                       NaN         NaN                   NaN
4                       NaN         NaN                   NaN
..                      ...         ...                   ...
820                    21.0         0.0                   0.0
821                    15.0         4.0                  25.0
822                    48.0         1.0                  23.0
823                    10.0         3.0                   0.0
824                    55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    NaN            NaN                 5.0
1                    NaN            NaN                 5.0
2                    NaN            NaN                 5.0
3                    NaN            NaN                 5.0
4                    NaN            NaN                 5.0
..                   ...            ...                 ...
820                  0.0             No                 5.0
821                  0.0             No                 3.0
822                  3.0            Yes                 0.0
823                  0.0             No                 3.0
824                  0.0             No                 1.0

[825 rows x 19 columns]

In [59]:
s1 = pd.DataFrame(s1_copy)
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
1,Male,28,Doctor,6.2,8.0,Normal,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
2,Male,28,Doctor,6.2,8.0,Normal,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,NaN,7.5,NaN,NaN,NaN,NaN,NaN,NaN,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5.0
821,Male,52,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3.0
822,Female,40,NaN,8.5,NaN,NaN,NaN,NaN,NaN,NaN,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0.0
823,Male,45,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3.0
824,Male,18,NaN,7.5,NaN,NaN,NaN,NaN,NaN,NaN,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1.0

In [60]:
s1.exercise_frequency.unique()

array([5., 3., 1., 0., 2., 4.])

In [61]:
s1['exercise_frequency'] = s1['exercise_frequency'].apply(lambda x: int(x) if type(x)==float else x)
s1['exercise_frequency'].unique()

array([5, 3, 1, 0, 2, 4], dtype=int64)

In [62]:
import pandas as pd
import numpy as np

s1_copy = s1.copy()

existing_categories = s1_copy['bmi_category'].dropna().unique()

s1_copy['bmi_category'] = s1_copy['bmi_category'].apply(lambda x: np.random.choice(existing_categories) if pd.isna(x) else x)


print(s1_copy)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27                   NaN             7.5           NaN
821    Male   52                   NaN             6.0           NaN
822  Female   40                   NaN             8.5           NaN
823    Male   45                   NaN             7.0           NaN
824    Male   18                   NaN             7.5           NaN

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1           Normal         125/80        75.0      10000.0           None
2           Normal         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight            NaN         NaN          NaN            NaN
821     Overweight            NaN         NaN          NaN            NaN
822  Normal Weight            NaN         NaN          NaN            NaN
823  Normal Weight            NaN         NaN          NaN            NaN
824         Normal            NaN         NaN          NaN            NaN

     sleep_efficiency  rem_sleep_percentage  deep_sleep_percentage  \
0                0.80                   NaN                    NaN
1                0.80                   NaN                    NaN
2                0.80                   NaN                    NaN
3                0.40                   NaN                    NaN
4                0.40                   NaN                    NaN
..                ...                   ...                    ...
820              0.91                  22.0                   57.0
821              0.74                  28.0                   57.0
822              0.55                  20.0                   32.0
823              0.76                  18.0                   72.0
824              0.63                  22.0                   23.0

     light_sleep_percentage  awakenings  caffeine_consumption  \
0                       NaN         NaN                   NaN
1                       NaN         NaN                   NaN
2                       NaN         NaN                   NaN
3                       NaN         NaN                   NaN
4                       NaN         NaN                   NaN
..                      ...         ...                   ...
820                    21.0         0.0                   0.0
821                    15.0         4.0                  25.0
822                    48.0         1.0                  23.0
823                    10.0         3.0                   0.0
824                    55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    NaN            NaN                   5
1                    NaN            NaN                   5
2                    NaN            NaN                   5
3                    NaN            NaN                   5
4                    NaN            NaN                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [63]:
s1 = pd.DataFrame(s1_copy)
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,Male,28,Doctor,6.2,8.0,Normal,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2,Male,28,Doctor,6.2,8.0,Normal,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,NaN,7.5,NaN,Normal Weight,NaN,NaN,NaN,NaN,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5
821,Male,52,NaN,6.0,NaN,Overweight,NaN,NaN,NaN,NaN,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3
822,Female,40,NaN,8.5,NaN,Normal Weight,NaN,NaN,NaN,NaN,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0
823,Male,45,NaN,7.0,NaN,Normal Weight,NaN,NaN,NaN,NaN,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3
824,Male,18,NaN,7.5,NaN,Normal,NaN,NaN,NaN,NaN,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1

In [64]:
s1.occupation.value_counts()

occupation
Nurse                   72
Doctor                  71
Engineer                63
Lawyer                  47
Teacher                 40
Accountant              37
Salesperson             32
Software Engineer        4
Scientist                4
Sales Representative     2
Manager                  1
Name: count, dtype: int64

In [65]:
s1.occupation.unique()

array(['Software Engineer', 'Doctor', 'Sales Representative', 'Teacher',
       'Nurse', 'Engineer', 'Accountant', 'Scientist', 'Lawyer',
       'Salesperson', 'Manager', nan], dtype=object)

In [66]:
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,Male,28,Doctor,6.2,8.0,Normal,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2,Male,28,Doctor,6.2,8.0,Normal,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,NaN,7.5,NaN,Normal Weight,NaN,NaN,NaN,NaN,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5
821,Male,52,NaN,6.0,NaN,Overweight,NaN,NaN,NaN,NaN,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3
822,Female,40,NaN,8.5,NaN,Normal Weight,NaN,NaN,NaN,NaN,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0
823,Male,45,NaN,7.0,NaN,Normal Weight,NaN,NaN,NaN,NaN,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3
824,Male,18,NaN,7.5,NaN,Normal,NaN,NaN,NaN,NaN,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1

In [67]:
import pandas as pd
import numpy as np

# Supongamos que tienes un DataFrame llamado 'df' con la columna 'occupation'

# Lista de trabajos disponibles
occupations = ['Software Engineer', 'Doctor', 'Sales Representative', 'Teacher', 'Nurse', 'Engineer', 'Accountant', 'Scientist', 'Lawyer', 'Salesperson', 'Manager']

# Crear una copia del DataFrame para evitar modificar el original
s1_copy = s1.copy()

# Sustituir los NaN en 'occupation' de manera aleatoria entre los trabajos disponibles
s1_copy['occupation'] = s1_copy['occupation'].apply(lambda x: np.random.choice(occupations) if pd.isna(x) else x)

# Mostrar el DataFrame resultante
print(s1_copy)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           NaN
821    Male   52            Accountant             6.0           NaN
822  Female   40                 Nurse             8.5           NaN
823    Male   45  Sales Representative             7.0           NaN
824    Male   18               Manager             7.5           NaN

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1           Normal         125/80        75.0      10000.0           None
2           Normal         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight            NaN         NaN          NaN            NaN
821     Overweight            NaN         NaN          NaN            NaN
822  Normal Weight            NaN         NaN          NaN            NaN
823  Normal Weight            NaN         NaN          NaN            NaN
824         Normal            NaN         NaN          NaN            NaN

     sleep_efficiency  rem_sleep_percentage  deep_sleep_percentage  \
0                0.80                   NaN                    NaN
1                0.80                   NaN                    NaN
2                0.80                   NaN                    NaN
3                0.40                   NaN                    NaN
4                0.40                   NaN                    NaN
..                ...                   ...                    ...
820              0.91                  22.0                   57.0
821              0.74                  28.0                   57.0
822              0.55                  20.0                   32.0
823              0.76                  18.0                   72.0
824              0.63                  22.0                   23.0

     light_sleep_percentage  awakenings  caffeine_consumption  \
0                       NaN         NaN                   NaN
1                       NaN         NaN                   NaN
2                       NaN         NaN                   NaN
3                       NaN         NaN                   NaN
4                       NaN         NaN                   NaN
..                      ...         ...                   ...
820                    21.0         0.0                   0.0
821                    15.0         4.0                  25.0
822                    48.0         1.0                  23.0
823                    10.0         3.0                   0.0
824                    55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    NaN            NaN                   5
1                    NaN            NaN                   5
2                    NaN            NaN                   5
3                    NaN            NaN                   5
4                    NaN            NaN                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [68]:
s1 = pd.DataFrame(s1_copy)
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,Male,28,Doctor,6.2,8.0,Normal,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2,Male,28,Doctor,6.2,8.0,Normal,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Software Engineer,7.5,NaN,Normal Weight,NaN,NaN,NaN,NaN,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5
821,Male,52,Accountant,6.0,NaN,Overweight,NaN,NaN,NaN,NaN,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3
822,Female,40,Nurse,8.5,NaN,Normal Weight,NaN,NaN,NaN,NaN,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0
823,Male,45,Sales Representative,7.0,NaN,Normal Weight,NaN,NaN,NaN,NaN,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3
824,Male,18,Manager,7.5,NaN,Normal,NaN,NaN,NaN,NaN,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1

In [69]:
s1.sleep_duration.unique()

array([ 6.1,  6.2,  5.9,  6.3,  7.8,  6. ,  6.5,  7.6,  7.7,  7.9,  6.4,
        7.5,  7.2,  5.8,  6.7,  7.3,  7.4,  7.1,  6.6,  6.9,  8. ,  6.8,
        8.1,  8.3,  8.5,  8.4,  8.2,  7. , 10. ,  9. ,  5. ,  5.5])

In [70]:
s1.stress_level.unique()

array([ 6.,  8.,  7.,  4.,  3.,  5., nan])

In [71]:
import pandas as pd
import numpy as np

# Supongamos que tienes un DataFrame llamado 's1' con las columnas 'sleep_duration' y 'stress_level'
# y deseas realizar la sustituci√≥n descrita.

# Crear una copia del DataFrame para evitar modificar el original
s1_copy = s1.copy()

# Crear un diccionario de mapeo entre valores √∫nicos de 'sleep_duration' y 'stress_level'
mapping_dict = {}

for index, row in s1_copy.iterrows():
    sleep_duration = row['sleep_duration']
    stress_level = row['stress_level']
    
    # Verificar si el valor de 'stress_level' no es NaN
    if not pd.isna(stress_level):
        if sleep_duration in mapping_dict:
            # Si el valor de 'sleep_duration' ya est√° en el diccionario, agregar 'stress_level' a la lista
            mapping_dict[sleep_duration].append(stress_level)
        else:
            # Si es la primera vez que se encuentra el valor de 'sleep_duration', crear una nueva lista
            mapping_dict[sleep_duration] = [stress_level]

# Funci√≥n para sustituir NaN en 'stress_level' basado en 'sleep_duration'
def replace_nan_stress_level(row):
    sleep_duration = row['sleep_duration']
    stress_level = row['stress_level']
    
    # Verificar si el valor de 'stress_level' es NaN
    if pd.isna(stress_level):
        # Si hay m√∫ltiples valores de 'stress_level' para este 'sleep_duration', elegir aleatoriamente uno
        if sleep_duration in mapping_dict:
            stress_level_options = mapping_dict[sleep_duration]
            stress_level = np.random.choice(stress_level_options)
        else:
            # Si no hay informaci√≥n previa, mantener NaN
            stress_level = np.nan
    
    return stress_level

# Aplicar la funci√≥n de sustituci√≥n a la columna 'stress_level'
s1_copy['stress_level'] = s1_copy.apply(replace_nan_stress_level, axis=1)

# Mostrar el DataFrame resultante
print(s1_copy)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           NaN
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1           Normal         125/80        75.0      10000.0           None
2           Normal         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight            NaN         NaN          NaN            NaN
821     Overweight            NaN         NaN          NaN            NaN
822  Normal Weight            NaN         NaN          NaN            NaN
823  Normal Weight            NaN         NaN          NaN            NaN
824         Normal            NaN         NaN          NaN            NaN

     sleep_efficiency  rem_sleep_percentage  deep_sleep_percentage  \
0                0.80                   NaN                    NaN
1                0.80                   NaN                    NaN
2                0.80                   NaN                    NaN
3                0.40                   NaN                    NaN
4                0.40                   NaN                    NaN
..                ...                   ...                    ...
820              0.91                  22.0                   57.0
821              0.74                  28.0                   57.0
822              0.55                  20.0                   32.0
823              0.76                  18.0                   72.0
824              0.63                  22.0                   23.0

     light_sleep_percentage  awakenings  caffeine_consumption  \
0                       NaN         NaN                   NaN
1                       NaN         NaN                   NaN
2                       NaN         NaN                   NaN
3                       NaN         NaN                   NaN
4                       NaN         NaN                   NaN
..                      ...         ...                   ...
820                    21.0         0.0                   0.0
821                    15.0         4.0                  25.0
822                    48.0         1.0                  23.0
823                    10.0         3.0                   0.0
824                    55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    NaN            NaN                   5
1                    NaN            NaN                   5
2                    NaN            NaN                   5
3                    NaN            NaN                   5
4                    NaN            NaN                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [72]:
s1 = pd.DataFrame(s1_copy)
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,Male,28,Doctor,6.2,8.0,Normal,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2,Male,28,Doctor,6.2,8.0,Normal,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Software Engineer,7.5,3.0,Normal Weight,NaN,NaN,NaN,NaN,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5
821,Male,52,Accountant,6.0,8.0,Overweight,NaN,NaN,NaN,NaN,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3
822,Female,40,Nurse,8.5,3.0,Normal Weight,NaN,NaN,NaN,NaN,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0
823,Male,45,Sales Representative,7.0,NaN,Normal Weight,NaN,NaN,NaN,NaN,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3
824,Male,18,Manager,7.5,4.0,Normal,NaN,NaN,NaN,NaN,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1

In [73]:
import pandas as pd

# Supongamos que tienes un DataFrame llamado 's1' con una columna llamada 'stress_level' que tiene NaN

# Crear una copia del DataFrame para evitar modificar el original
s1_copy = s1.copy()

# Calcular la moda de la columna 'stress_level'
mode_stress_level = s1_copy['stress_level'].mode().iloc[0]

# Sustituir los NaN en 'stress_level' con la moda
s1_copy['stress_level'].fillna(mode_stress_level, inplace=True)

# Mostrar el DataFrame resultante
print(s1_copy)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           3.0
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1           Normal         125/80        75.0      10000.0           None
2           Normal         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight            NaN         NaN          NaN            NaN
821     Overweight            NaN         NaN          NaN            NaN
822  Normal Weight            NaN         NaN          NaN            NaN
823  Normal Weight            NaN         NaN          NaN            NaN
824         Normal            NaN         NaN          NaN            NaN

     sleep_efficiency  rem_sleep_percentage  deep_sleep_percentage  \
0                0.80                   NaN                    NaN
1                0.80                   NaN                    NaN
2                0.80                   NaN                    NaN
3                0.40                   NaN                    NaN
4                0.40                   NaN                    NaN
..                ...                   ...                    ...
820              0.91                  22.0                   57.0
821              0.74                  28.0                   57.0
822              0.55                  20.0                   32.0
823              0.76                  18.0                   72.0
824              0.63                  22.0                   23.0

     light_sleep_percentage  awakenings  caffeine_consumption  \
0                       NaN         NaN                   NaN
1                       NaN         NaN                   NaN
2                       NaN         NaN                   NaN
3                       NaN         NaN                   NaN
4                       NaN         NaN                   NaN
..                      ...         ...                   ...
820                    21.0         0.0                   0.0
821                    15.0         4.0                  25.0
822                    48.0         1.0                  23.0
823                    10.0         3.0                   0.0
824                    55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    NaN            NaN                   5
1                    NaN            NaN                   5
2                    NaN            NaN                   5
3                    NaN            NaN                   5
4                    NaN            NaN                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [74]:
s1 = pd.DataFrame(s1_copy)
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,Male,28,Doctor,6.2,8.0,Normal,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2,Male,28,Doctor,6.2,8.0,Normal,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Software Engineer,7.5,3.0,Normal Weight,NaN,NaN,NaN,NaN,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5
821,Male,52,Accountant,6.0,8.0,Overweight,NaN,NaN,NaN,NaN,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3
822,Female,40,Nurse,8.5,3.0,Normal Weight,NaN,NaN,NaN,NaN,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0
823,Male,45,Sales Representative,7.0,3.0,Normal Weight,NaN,NaN,NaN,NaN,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3
824,Male,18,Manager,7.5,4.0,Normal,NaN,NaN,NaN,NaN,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1

In [75]:
s1.stress_level.unique()

array([6., 8., 7., 4., 3., 5.])

In [76]:
s1.isna().sum()

gender                      0
age                         0
occupation                  0
sleep_duration              0
stress_level                0
bmi_category                0
blood_pressure            452
heart_rate                452
daily_steps               452
sleep_disorder            452
sleep_efficiency            0
rem_sleep_percentage      373
deep_sleep_percentage     373
light_sleep_percentage    373
awakenings                373
caffeine_consumption      373
alcohol_consumption       373
smoking_status            373
exercise_frequency          0
dtype: int64

In [77]:
s1.bmi_category.unique()

array(['Overweight', 'Normal', 'Obese', 'Normal Weight'], dtype=object)

In [78]:
import pandas as pd

s1_copy = s1.copy()

s1_copy['bmi_category'] = s1_copy['bmi_category'].replace('Normal', 'Normal Weight')

print(s1_copy)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           3.0
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1    Normal Weight         125/80        75.0      10000.0           None
2    Normal Weight         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight            NaN         NaN          NaN            NaN
821     Overweight            NaN         NaN          NaN            NaN
822  Normal Weight            NaN         NaN          NaN            NaN
823  Normal Weight            NaN         NaN          NaN            NaN
824  Normal Weight            NaN         NaN          NaN            NaN

     sleep_efficiency  rem_sleep_percentage  deep_sleep_percentage  \
0                0.80                   NaN                    NaN
1                0.80                   NaN                    NaN
2                0.80                   NaN                    NaN
3                0.40                   NaN                    NaN
4                0.40                   NaN                    NaN
..                ...                   ...                    ...
820              0.91                  22.0                   57.0
821              0.74                  28.0                   57.0
822              0.55                  20.0                   32.0
823              0.76                  18.0                   72.0
824              0.63                  22.0                   23.0

     light_sleep_percentage  awakenings  caffeine_consumption  \
0                       NaN         NaN                   NaN
1                       NaN         NaN                   NaN
2                       NaN         NaN                   NaN
3                       NaN         NaN                   NaN
4                       NaN         NaN                   NaN
..                      ...         ...                   ...
820                    21.0         0.0                   0.0
821                    15.0         4.0                  25.0
822                    48.0         1.0                  23.0
823                    10.0         3.0                   0.0
824                    55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    NaN            NaN                   5
1                    NaN            NaN                   5
2                    NaN            NaN                   5
3                    NaN            NaN                   5
4                    NaN            NaN                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [79]:
s1 = pd.DataFrame(s1_copy)
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Software Engineer,7.5,3.0,Normal Weight,NaN,NaN,NaN,NaN,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5
821,Male,52,Accountant,6.0,8.0,Overweight,NaN,NaN,NaN,NaN,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3
822,Female,40,Nurse,8.5,3.0,Normal Weight,NaN,NaN,NaN,NaN,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0
823,Male,45,Sales Representative,7.0,3.0,Normal Weight,NaN,NaN,NaN,NaN,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3
824,Male,18,Manager,7.5,4.0,Normal Weight,NaN,NaN,NaN,NaN,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1

In [80]:
s1.blood_pressure.unique()

array(['126/83', '125/80', '140/90', '120/80', '132/87', '130/86',
       '117/76', '118/76', '128/85', '131/86', '128/84', '115/75',
       '135/88', '129/84', '130/85', '115/78', '119/77', '121/79',
       '125/82', '135/90', '122/80', '142/92', '140/95', '139/91',
       '118/75', nan], dtype=object)

In [81]:
import pandas as pd
import numpy as np

# Supongamos que tienes un DataFrame llamado 's1' con las columnas 'bmi_category' y 'blood_pressure'
# y deseas realizar la sustituci√≥n descrita.

# Crear una copia del DataFrame para evitar modificar el original
s1_copy = s1.copy()

# Crear un diccionario de mapeo entre valores √∫nicos de 'bmi_category' y 'blood_pressure'
mapping_dict = {}

for index, row in s1_copy.iterrows():
    bmi_category = row['bmi_category']
    blood_pressure = row['blood_pressure']
    
    # Verificar si el valor de 'blood_pressure' no es NaN
    if not pd.isna(blood_pressure):
        if bmi_category in mapping_dict:
            # Si el valor de 'bmi_category' ya est√° en el diccionario, agregar 'blood_pressure' a la lista
            mapping_dict[bmi_category].append(blood_pressure)
        else:
            # Si es la primera vez que se encuentra el valor de 'bmi_category', crear una nueva lista
            mapping_dict[bmi_category] = [blood_pressure]

# Funci√≥n para sustituir NaN en 'blood_pressure' basado en 'bmi_category'
def replace_nan_blood_pressure(row):
    bmi_category = row['bmi_category']
    blood_pressure = row['blood_pressure']
    
    # Verificar si el valor de 'blood_pressure' es NaN
    if pd.isna(blood_pressure):
        # Si hay m√∫ltiples valores de 'blood_pressure' para este 'bmi_category', elegir aleatoriamente uno
        if bmi_category in mapping_dict:
            blood_pressure_options = mapping_dict[bmi_category]
            blood_pressure = np.random.choice(blood_pressure_options)
        else:
            # Si no hay informaci√≥n previa, mantener NaN
            blood_pressure = np.nan
    
    return blood_pressure

# Aplicar la funci√≥n de sustituci√≥n a la columna 'blood_pressure'
s1_copy['blood_pressure'] = s1_copy.apply(replace_nan_blood_pressure, axis=1)

# Mostrar el DataFrame resultante
print(s1_copy)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           3.0
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1    Normal Weight         125/80        75.0      10000.0           None
2    Normal Weight         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight         130/85         NaN          NaN            NaN
821     Overweight         130/85         NaN          NaN            NaN
822  Normal Weight         120/80         NaN          NaN            NaN
823  Normal Weight         118/76         NaN          NaN            NaN
824  Normal Weight         120/80         NaN          NaN            NaN

     sleep_efficiency  rem_sleep_percentage  deep_sleep_percentage  \
0                0.80                   NaN                    NaN
1                0.80                   NaN                    NaN
2                0.80                   NaN                    NaN
3                0.40                   NaN                    NaN
4                0.40                   NaN                    NaN
..                ...                   ...                    ...
820              0.91                  22.0                   57.0
821              0.74                  28.0                   57.0
822              0.55                  20.0                   32.0
823              0.76                  18.0                   72.0
824              0.63                  22.0                   23.0

     light_sleep_percentage  awakenings  caffeine_consumption  \
0                       NaN         NaN                   NaN
1                       NaN         NaN                   NaN
2                       NaN         NaN                   NaN
3                       NaN         NaN                   NaN
4                       NaN         NaN                   NaN
..                      ...         ...                   ...
820                    21.0         0.0                   0.0
821                    15.0         4.0                  25.0
822                    48.0         1.0                  23.0
823                    10.0         3.0                   0.0
824                    55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    NaN            NaN                   5
1                    NaN            NaN                   5
2                    NaN            NaN                   5
3                    NaN            NaN                   5
4                    NaN            NaN                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [82]:
s1 = pd.DataFrame(s1_copy)
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Software Engineer,7.5,3.0,Normal Weight,130/85,NaN,NaN,NaN,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5
821,Male,52,Accountant,6.0,8.0,Overweight,130/85,NaN,NaN,NaN,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3
822,Female,40,Nurse,8.5,3.0,Normal Weight,120/80,NaN,NaN,NaN,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0
823,Male,45,Sales Representative,7.0,3.0,Normal Weight,118/76,NaN,NaN,NaN,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3
824,Male,18,Manager,7.5,4.0,Normal Weight,120/80,NaN,NaN,NaN,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1

In [83]:
s1.blood_pressure.unique()

array(['126/83', '125/80', '140/90', '120/80', '132/87', '130/86',
       '117/76', '118/76', '128/85', '131/86', '128/84', '115/75',
       '135/88', '129/84', '130/85', '115/78', '119/77', '121/79',
       '125/82', '135/90', '122/80', '142/92', '140/95', '139/91',
       '118/75'], dtype=object)

In [84]:
import pandas as pd
import numpy as np

# Supongamos que tienes un DataFrame llamado 's1' con las columnas 'bmi_category' y 'blood_pressure'
# y deseas realizar la sustituci√≥n descrita.

# Crear una copia del DataFrame para evitar modificar el original
s1_copy = s1.copy()

# Crear un diccionario de mapeo entre valores √∫nicos de 'bmi_category' y 'blood_pressure'
mapping_dict = {}

for index, row in s1_copy.iterrows():
    blood_pressure = row['blood_pressure']
    heart_rate = row['heart_rate']
    
    # Verificar si el valor de 'blood_pressure' no es NaN
    if not pd.isna(heart_rate):
        if blood_pressure in mapping_dict:
            # Si el valor de 'bmi_category' ya est√° en el diccionario, agregar 'blood_pressure' a la lista
            mapping_dict[blood_pressure].append(heart_rate)
        else:
            # Si es la primera vez que se encuentra el valor de 'bmi_category', crear una nueva lista
            mapping_dict[blood_pressure] = [heart_rate]

# Funci√≥n para sustituir NaN en 'blood_pressure' basado en 'bmi_category'
def replace_nan_heart_rate(row):
    blood_pressure = row['blood_pressure']
    heart_rate = row['heart_rate']
    
    # Verificar si el valor de 'blood_pressure' es NaN
    if pd.isna(heart_rate):
        # Si hay m√∫ltiples valores de 'blood_pressure' para este 'bmi_category', elegir aleatoriamente uno
        if blood_pressure in mapping_dict:
            heart_rate_options = mapping_dict[blood_pressure]
            heart_rate = np.random.choice(heart_rate_options)
        else:
            # Si no hay informaci√≥n previa, mantener NaN
            heart_rate = np.nan
    
    return heart_rate

# Aplicar la funci√≥n de sustituci√≥n a la columna 'blood_pressure'
s1_copy['heart_rate'] = s1_copy.apply(replace_nan_heart_rate, axis=1)

# Mostrar el DataFrame resultante
print(s1_copy)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           3.0
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1    Normal Weight         125/80        75.0      10000.0           None
2    Normal Weight         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight         130/85        68.0          NaN            NaN
821     Overweight         130/85        70.0          NaN            NaN
822  Normal Weight         120/80        70.0          NaN            NaN
823  Normal Weight         118/76        68.0          NaN            NaN
824  Normal Weight         120/80        70.0          NaN            NaN

     sleep_efficiency  rem_sleep_percentage  deep_sleep_percentage  \
0                0.80                   NaN                    NaN
1                0.80                   NaN                    NaN
2                0.80                   NaN                    NaN
3                0.40                   NaN                    NaN
4                0.40                   NaN                    NaN
..                ...                   ...                    ...
820              0.91                  22.0                   57.0
821              0.74                  28.0                   57.0
822              0.55                  20.0                   32.0
823              0.76                  18.0                   72.0
824              0.63                  22.0                   23.0

     light_sleep_percentage  awakenings  caffeine_consumption  \
0                       NaN         NaN                   NaN
1                       NaN         NaN                   NaN
2                       NaN         NaN                   NaN
3                       NaN         NaN                   NaN
4                       NaN         NaN                   NaN
..                      ...         ...                   ...
820                    21.0         0.0                   0.0
821                    15.0         4.0                  25.0
822                    48.0         1.0                  23.0
823                    10.0         3.0                   0.0
824                    55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    NaN            NaN                   5
1                    NaN            NaN                   5
2                    NaN            NaN                   5
3                    NaN            NaN                   5
4                    NaN            NaN                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [85]:
s1 = pd.DataFrame(s1_copy)
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Software Engineer,7.5,3.0,Normal Weight,130/85,68.0,NaN,NaN,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5
821,Male,52,Accountant,6.0,8.0,Overweight,130/85,70.0,NaN,NaN,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3
822,Female,40,Nurse,8.5,3.0,Normal Weight,120/80,70.0,NaN,NaN,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0
823,Male,45,Sales Representative,7.0,3.0,Normal Weight,118/76,68.0,NaN,NaN,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3
824,Male,18,Manager,7.5,4.0,Normal Weight,120/80,70.0,NaN,NaN,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1

In [86]:
s1.heart_rate.unique()

array([77., 75., 85., 82., 70., 80., 78., 69., 72., 68., 76., 81., 65.,
       84., 74., 67., 73., 83., 86.])

In [87]:
s1.daily_steps.unique()

array([ 4200., 10000.,  3000.,  3500.,  8000.,  4000.,  4100.,  6800.,
        5000.,  7000.,  5500.,  5200.,  5600.,  3300.,  4800.,  7500.,
        7300.,  6200.,  6000.,  3700.,    nan])

In [88]:
import pandas as pd
import numpy as np

# Supongamos que tienes un DataFrame llamado 's1' con las columnas 'bmi_category' y 'blood_pressure'
# y deseas realizar la sustituci√≥n descrita.

# Crear una copia del DataFrame para evitar modificar el original
s1_copy = s1.copy()

# Crear un diccionario de mapeo entre valores √∫nicos de 'bmi_category' y 'blood_pressure'
mapping_dict = {}

for index, row in s1_copy.iterrows():
    blood_pressure = row['blood_pressure']
    daily_steps = row['daily_steps']
    
    # Verificar si el valor de 'blood_pressure' no es NaN
    if not pd.isna(daily_steps):
        if blood_pressure in mapping_dict:
            # Si el valor de 'bmi_category' ya est√° en el diccionario, agregar 'blood_pressure' a la lista
            mapping_dict[blood_pressure].append(daily_steps)
        else:
            # Si es la primera vez que se encuentra el valor de 'bmi_category', crear una nueva lista
            mapping_dict[blood_pressure] = [daily_steps]

# Funci√≥n para sustituir NaN en 'blood_pressure' basado en 'bmi_category'
def replace_nan_daily_steps(row):
    blood_pressure = row['blood_pressure']
    daily_steps = row['daily_steps']
    
    # Verificar si el valor de 'blood_pressure' es NaN
    if pd.isna(daily_steps):
        # Si hay m√∫ltiples valores de 'blood_pressure' para este 'bmi_category', elegir aleatoriamente uno
        if blood_pressure in mapping_dict:
            daily_steps_options = mapping_dict[blood_pressure]
            daily_steps = np.random.choice(daily_steps_options)
        else:
            # Si no hay informaci√≥n previa, mantener NaN
            daily_steps = np.nan
    
    return daily_steps

# Aplicar la funci√≥n de sustituci√≥n a la columna 'blood_pressure'
s1_copy['daily_steps'] = s1_copy.apply(replace_nan_daily_steps, axis=1)

# Mostrar el DataFrame resultante
print(s1_copy)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           3.0
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1    Normal Weight         125/80        75.0      10000.0           None
2    Normal Weight         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight         130/85        68.0       8000.0            NaN
821     Overweight         130/85        70.0       8000.0            NaN
822  Normal Weight         120/80        70.0       8000.0            NaN
823  Normal Weight         118/76        68.0       7000.0            NaN
824  Normal Weight         120/80        70.0       8000.0            NaN

     sleep_efficiency  rem_sleep_percentage  deep_sleep_percentage  \
0                0.80                   NaN                    NaN
1                0.80                   NaN                    NaN
2                0.80                   NaN                    NaN
3                0.40                   NaN                    NaN
4                0.40                   NaN                    NaN
..                ...                   ...                    ...
820              0.91                  22.0                   57.0
821              0.74                  28.0                   57.0
822              0.55                  20.0                   32.0
823              0.76                  18.0                   72.0
824              0.63                  22.0                   23.0

     light_sleep_percentage  awakenings  caffeine_consumption  \
0                       NaN         NaN                   NaN
1                       NaN         NaN                   NaN
2                       NaN         NaN                   NaN
3                       NaN         NaN                   NaN
4                       NaN         NaN                   NaN
..                      ...         ...                   ...
820                    21.0         0.0                   0.0
821                    15.0         4.0                  25.0
822                    48.0         1.0                  23.0
823                    10.0         3.0                   0.0
824                    55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    NaN            NaN                   5
1                    NaN            NaN                   5
2                    NaN            NaN                   5
3                    NaN            NaN                   5
4                    NaN            NaN                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [89]:
s1 = pd.DataFrame(s1_copy)
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Software Engineer,7.5,3.0,Normal Weight,130/85,68.0,8000.0,NaN,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5
821,Male,52,Accountant,6.0,8.0,Overweight,130/85,70.0,8000.0,NaN,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3
822,Female,40,Nurse,8.5,3.0,Normal Weight,120/80,70.0,8000.0,NaN,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0
823,Male,45,Sales Representative,7.0,3.0,Normal Weight,118/76,68.0,7000.0,NaN,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3
824,Male,18,Manager,7.5,4.0,Normal Weight,120/80,70.0,8000.0,NaN,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1

In [90]:
import pandas as pd
import numpy as np

# Supongamos que tienes un DataFrame llamado 's1' con las columnas 'bmi_category' y 'blood_pressure'
# y deseas realizar la sustituci√≥n descrita.

# Crear una copia del DataFrame para evitar modificar el original
s1_copy = s1.copy()

# Crear un diccionario de mapeo entre valores √∫nicos de 'bmi_category' y 'blood_pressure'
mapping_dict = {}

for index, row in s1_copy.iterrows():
    blood_pressure = row['blood_pressure']
    sleep_disorder = row['sleep_disorder']
    
    # Verificar si el valor de 'blood_pressure' no es NaN
    if not pd.isna(sleep_disorder):
        if blood_pressure in mapping_dict:
            # Si el valor de 'bmi_category' ya est√° en el diccionario, agregar 'blood_pressure' a la lista
            mapping_dict[blood_pressure].append(sleep_disorder)
        else:
            # Si es la primera vez que se encuentra el valor de 'bmi_category', crear una nueva lista
            mapping_dict[blood_pressure] = [sleep_disorder]

# Funci√≥n para sustituir NaN en 'blood_pressure' basado en 'bmi_category'
def replace_nan_sleep_disorder(row):
    blood_pressure = row['blood_pressure']
    sleep_disorder = row['sleep_disorder']
    
    # Verificar si el valor de 'blood_pressure' es NaN
    if pd.isna(sleep_disorder):
        # Si hay m√∫ltiples valores de 'blood_pressure' para este 'bmi_category', elegir aleatoriamente uno
        if blood_pressure in mapping_dict:
            sleep_disorder_options = mapping_dict[blood_pressure]
            sleep_disorder = np.random.choice(sleep_disorder_options)
        else:
            # Si no hay informaci√≥n previa, mantener NaN
            sleep_disorder = np.nan
    
    return sleep_disorder

# Aplicar la funci√≥n de sustituci√≥n a la columna 'blood_pressure'
s1_copy['sleep_disorder'] = s1_copy.apply(replace_nan_sleep_disorder, axis=1)

# Mostrar el DataFrame resultante
print(s1_copy)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           3.0
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1    Normal Weight         125/80        75.0      10000.0           None
2    Normal Weight         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight         130/85        68.0       8000.0           None
821     Overweight         130/85        70.0       8000.0       Insomnia
822  Normal Weight         120/80        70.0       8000.0           None
823  Normal Weight         118/76        68.0       7000.0           None
824  Normal Weight         120/80        70.0       8000.0           None

     sleep_efficiency  rem_sleep_percentage  deep_sleep_percentage  \
0                0.80                   NaN                    NaN
1                0.80                   NaN                    NaN
2                0.80                   NaN                    NaN
3                0.40                   NaN                    NaN
4                0.40                   NaN                    NaN
..                ...                   ...                    ...
820              0.91                  22.0                   57.0
821              0.74                  28.0                   57.0
822              0.55                  20.0                   32.0
823              0.76                  18.0                   72.0
824              0.63                  22.0                   23.0

     light_sleep_percentage  awakenings  caffeine_consumption  \
0                       NaN         NaN                   NaN
1                       NaN         NaN                   NaN
2                       NaN         NaN                   NaN
3                       NaN         NaN                   NaN
4                       NaN         NaN                   NaN
..                      ...         ...                   ...
820                    21.0         0.0                   0.0
821                    15.0         4.0                  25.0
822                    48.0         1.0                  23.0
823                    10.0         3.0                   0.0
824                    55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    NaN            NaN                   5
1                    NaN            NaN                   5
2                    NaN            NaN                   5
3                    NaN            NaN                   5
4                    NaN            NaN                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [91]:
s1 = pd.DataFrame(s1_copy)
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Software Engineer,7.5,3.0,Normal Weight,130/85,68.0,8000.0,None,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5
821,Male,52,Accountant,6.0,8.0,Overweight,130/85,70.0,8000.0,Insomnia,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3
822,Female,40,Nurse,8.5,3.0,Normal Weight,120/80,70.0,8000.0,None,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0
823,Male,45,Sales Representative,7.0,3.0,Normal Weight,118/76,68.0,7000.0,None,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3
824,Male,18,Manager,7.5,4.0,Normal Weight,120/80,70.0,8000.0,None,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1

In [92]:
s1.isna().sum()

gender                      0
age                         0
occupation                  0
sleep_duration              0
stress_level                0
bmi_category                0
blood_pressure              0
heart_rate                  0
daily_steps                 0
sleep_disorder              0
sleep_efficiency            0
rem_sleep_percentage      373
deep_sleep_percentage     373
light_sleep_percentage    373
awakenings                373
caffeine_consumption      373
alcohol_consumption       373
smoking_status            373
exercise_frequency          0
dtype: int64

In [93]:
import pandas as pd
import numpy as np

# Supongamos que tienes un DataFrame llamado 's1' con las columnas 'sleep_efficiency', 'rem_sleep_percentage', 'deep_sleep_percentage' y 'light_sleep_percentage'

# Crear una copia del DataFrame para evitar modificar el original
s1_copy = s1.copy()

# Crear un diccionario de mapeo entre valores √∫nicos de 'sleep_efficiency' y 'rem_sleep_percentage'
mapping_dict_rem_sleep = {}

for index, row in s1_copy.iterrows():
    sleep_efficiency = row['sleep_efficiency']
    rem_sleep_percentage = row['rem_sleep_percentage']
    
    # Verificar si el valor de 'rem_sleep_percentage' no es NaN
    if not pd.isna(rem_sleep_percentage):
        if sleep_efficiency in mapping_dict_rem_sleep:
            # Si el valor de 'sleep_efficiency' ya est√° en el diccionario, agregar 'rem_sleep_percentage' a la lista
            mapping_dict_rem_sleep[sleep_efficiency].append(rem_sleep_percentage)
        else:
            # Si es la primera vez que se encuentra el valor de 'sleep_efficiency', crear una nueva lista
            mapping_dict_rem_sleep[sleep_efficiency] = [rem_sleep_percentage]

# Funci√≥n para sustituir NaN en 'rem_sleep_percentage' basado en 'sleep_efficiency'
def replace_nan_rem_sleep_percentage(row):
    sleep_efficiency = row['sleep_efficiency']
    rem_sleep_percentage = row['rem_sleep_percentage']
    
    # Verificar si el valor de 'rem_sleep_percentage' es NaN
    if pd.isna(rem_sleep_percentage):
        # Si hay m√∫ltiples valores de 'rem_sleep_percentage' para este 'sleep_efficiency', elegir aleatoriamente uno
        if sleep_efficiency in mapping_dict_rem_sleep:
            rem_sleep_percentage_options = mapping_dict_rem_sleep[sleep_efficiency]
            rem_sleep_percentage = np.random.choice(rem_sleep_percentage_options)
        else:
            # Si no hay informaci√≥n previa, mantener NaN
            rem_sleep_percentage = np.nan
    
    return rem_sleep_percentage

# Aplicar la funci√≥n de sustituci√≥n a la columna 'rem_sleep_percentage'
s1_copy['rem_sleep_percentage'] = s1_copy.apply(replace_nan_rem_sleep_percentage, axis=1)

# Crear un diccionario de mapeo entre valores √∫nicos de 'sleep_efficiency' y 'deep_sleep_percentage'
mapping_dict_deep_sleep = {}

for index, row in s1_copy.iterrows():
    sleep_efficiency = row['sleep_efficiency']
    deep_sleep_percentage = row['deep_sleep_percentage']
    
    # Verificar si el valor de 'deep_sleep_percentage' no es NaN
    if not pd.isna(deep_sleep_percentage):
        if sleep_efficiency in mapping_dict_deep_sleep:
            # Si el valor de 'sleep_efficiency' ya est√° en el diccionario, agregar 'deep_sleep_percentage' a la lista
            mapping_dict_deep_sleep[sleep_efficiency].append(deep_sleep_percentage)
        else:
            # Si es la primera vez que se encuentra el valor de 'sleep_efficiency', crear una nueva lista
            mapping_dict_deep_sleep[sleep_efficiency] = [deep_sleep_percentage]

# Funci√≥n para sustituir NaN en 'deep_sleep_percentage' basado en 'sleep_efficiency'
def replace_nan_deep_sleep_percentage(row):
    sleep_efficiency = row['sleep_efficiency']
    deep_sleep_percentage = row['deep_sleep_percentage']
    
    # Verificar si el valor de 'deep_sleep_percentage' es NaN
    if pd.isna(deep_sleep_percentage):
        # Si hay m√∫ltiples valores de 'deep_sleep_percentage' para este 'sleep_efficiency', elegir aleatoriamente uno
        if sleep_efficiency in mapping_dict_deep_sleep:
            deep_sleep_percentage_options = mapping_dict_deep_sleep[sleep_efficiency]
            deep_sleep_percentage = np.random.choice(deep_sleep_percentage_options)
        else:
            # Si no hay informaci√≥n previa, mantener NaN
            deep_sleep_percentage = np.nan
    
    return deep_sleep_percentage

# Aplicar la funci√≥n de sustituci√≥n a la columna 'deep_sleep_percentage'
s1_copy['deep_sleep_percentage'] = s1_copy.apply(replace_nan_deep_sleep_percentage, axis=1)

# Crear un diccionario de mapeo entre valores √∫nicos de 'sleep_efficiency' y 'light_sleep_percentage'
mapping_dict_light_sleep = {}

for index, row in s1_copy.iterrows():
    sleep_efficiency = row['sleep_efficiency']
    light_sleep_percentage = row['light_sleep_percentage']
    
    # Verificar si el valor de 'light_sleep_percentage' no es NaN
    if not pd.isna(light_sleep_percentage):
        if sleep_efficiency in mapping_dict_light_sleep:
            # Si el valor de 'sleep_efficiency' ya est√° en el diccionario, agregar 'light_sleep_percentage' a la lista
            mapping_dict_light_sleep[sleep_efficiency].append(light_sleep_percentage)
        else:
            # Si es la primera vez que se encuentra el valor de 'sleep_efficiency', crear una nueva lista
            mapping_dict_light_sleep[sleep_efficiency] = [light_sleep_percentage]

# Funci√≥n para sustituir NaN en 'light_sleep_percentage' basado en 'sleep_efficiency'
def replace_nan_light_sleep_percentage(row):
    sleep_efficiency = row['sleep_efficiency']
    light_sleep_percentage = row['light_sleep_percentage']
    
    # Verificar si el valor de 'light_sleep_percentage' es NaN
    if pd.isna(light_sleep_percentage):
        # Si hay m√∫ltiples valores de 'light_sleep_percentage' para este 'sleep_efficiency', elegir aleatoriamente uno
        if sleep_efficiency in mapping_dict_light_sleep:
            light_sleep_percentage_options = mapping_dict_light_sleep[sleep_efficiency]
            light_sleep_percentage = np.random.choice(light_sleep_percentage_options)
        else:
            # Si no hay informaci√≥n previa, mantener NaN
            light_sleep_percentage = np.nan
    
    return light_sleep_percentage

# Aplicar la funci√≥n de sustituci√≥n a la columna 'light_sleep_percentage'
s1_copy['light_sleep_percentage'] = s1_copy.apply(replace_nan_light_sleep_percentage, axis=1)

# Asegurarse de que la suma de los tres porcentajes sea 100.0
s1_copy['total_sleep_percentage'] = s1_copy['rem_sleep_percentage'] + s1_copy['deep_sleep_percentage'] + s1_copy['light_sleep_percentage']

# Normalizar los porcentajes para que sumen 100.0
s1_copy[['rem_sleep_percentage', 'deep_sleep_percentage', 'light_sleep_percentage']] = s1_copy[['rem_sleep_percentage', 'deep_sleep_percentage', 'light_sleep_percentage']].div(s1_copy['total_sleep_percentage'], axis=0) * 100.0

# Eliminar la columna temporal 'total_sleep_percentage'
s1_copy.drop(columns=['total_sleep_percentage'], inplace=True)

# Mostrar el DataFrame resultante
print(s1_copy)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           3.0
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1    Normal Weight         125/80        75.0      10000.0           None
2    Normal Weight         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight         130/85        68.0       8000.0           None
821     Overweight         130/85        70.0       8000.0       Insomnia
822  Normal Weight         120/80        70.0       8000.0           None
823  Normal Weight         118/76        68.0       7000.0           None
824  Normal Weight         120/80        70.0       8000.0           None

     sleep_efficiency  rem_sleep_percentage  deep_sleep_percentage  \
0                0.80             26.666667              57.142857
1                0.80             24.778761              57.522124
2                0.80             25.925926              55.555556
3                0.40                   NaN                    NaN
4                0.40                   NaN                    NaN
..                ...                   ...                    ...
820              0.91             22.000000              57.000000
821              0.74             28.000000              57.000000
822              0.55             20.000000              32.000000
823              0.76             18.000000              72.000000
824              0.63             22.000000              23.000000

     light_sleep_percentage  awakenings  caffeine_consumption  \
0                 16.190476         NaN                   NaN
1                 17.699115         NaN                   NaN
2                 18.518519         NaN                   NaN
3                       NaN         NaN                   NaN
4                       NaN         NaN                   NaN
..                      ...         ...                   ...
820               21.000000         0.0                   0.0
821               15.000000         4.0                  25.0
822               48.000000         1.0                  23.0
823               10.000000         3.0                   0.0
824               55.000000         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    NaN            NaN                   5
1                    NaN            NaN                   5
2                    NaN            NaN                   5
3                    NaN            NaN                   5
4                    NaN            NaN                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [94]:
s1 = pd.DataFrame(s1_copy)
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,26.666667,57.142857,16.190476,NaN,NaN,NaN,NaN,5
1,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,24.778761,57.522124,17.699115,NaN,NaN,NaN,NaN,5
2,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,25.925926,55.555556,18.518519,NaN,NaN,NaN,NaN,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Software Engineer,7.5,3.0,Normal Weight,130/85,68.0,8000.0,None,0.91,22.000000,57.000000,21.000000,0.0,0.0,0.0,No,5
821,Male,52,Accountant,6.0,8.0,Overweight,130/85,70.0,8000.0,Insomnia,0.74,28.000000,57.000000,15.000000,4.0,25.0,0.0,No,3
822,Female,40,Nurse,8.5,3.0,Normal Weight,120/80,70.0,8000.0,None,0.55,20.000000,32.000000,48.000000,1.0,23.0,3.0,Yes,0
823,Male,45,Sales Representative,7.0,3.0,Normal Weight,118/76,68.0,7000.0,None,0.76,18.000000,72.000000,10.000000,3.0,0.0,0.0,No,3
824,Male,18,Manager,7.5,4.0,Normal Weight,120/80,70.0,8000.0,None,0.63,22.000000,23.000000,55.000000,1.0,50.0,0.0,No,1

In [95]:
import pandas as pd
import numpy as np

# Supongamos que tienes un DataFrame llamado 's1' con las columnas 'rem_sleep_percentage', 'deep_sleep_percentage' y 'light_sleep_percentage'

# Crear una copia del DataFrame para evitar modificar el original
s1_copy = s1.copy()

# Sustituir NaN por "unknown" en las tres columnas
s1_copy['rem_sleep_percentage'].fillna('unknown', inplace=True)
s1_copy['deep_sleep_percentage'].fillna('unknown', inplace=True)
s1_copy['light_sleep_percentage'].fillna('unknown', inplace=True)

# Mostrar el DataFrame resultante
print(s1_copy)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           3.0
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1    Normal Weight         125/80        75.0      10000.0           None
2    Normal Weight         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight         130/85        68.0       8000.0           None
821     Overweight         130/85        70.0       8000.0       Insomnia
822  Normal Weight         120/80        70.0       8000.0           None
823  Normal Weight         118/76        68.0       7000.0           None
824  Normal Weight         120/80        70.0       8000.0           None

     sleep_efficiency rem_sleep_percentage deep_sleep_percentage  \
0                0.80            26.666667             57.142857
1                0.80            24.778761             57.522124
2                0.80            25.925926             55.555556
3                0.40              unknown               unknown
4                0.40              unknown               unknown
..                ...                  ...                   ...
820              0.91                 22.0                  57.0
821              0.74                 28.0                  57.0
822              0.55                 20.0                  32.0
823              0.76                 18.0                  72.0
824              0.63                 22.0                  23.0

    light_sleep_percentage  awakenings  caffeine_consumption  \
0                16.190476         NaN                   NaN
1                17.699115         NaN                   NaN
2                18.518519         NaN                   NaN
3                  unknown         NaN                   NaN
4                  unknown         NaN                   NaN
..                     ...         ...                   ...
820                   21.0         0.0                   0.0
821                   15.0         4.0                  25.0
822                   48.0         1.0                  23.0
823                   10.0         3.0                   0.0
824                   55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    NaN            NaN                   5
1                    NaN            NaN                   5
2                    NaN            NaN                   5
3                    NaN            NaN                   5
4                    NaN            NaN                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [96]:
s1 = pd.DataFrame(s1_copy)
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,26.666667,57.142857,16.190476,NaN,NaN,NaN,NaN,5
1,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,24.778761,57.522124,17.699115,NaN,NaN,NaN,NaN,5
2,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,25.925926,55.555556,18.518519,NaN,NaN,NaN,NaN,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,unknown,unknown,unknown,NaN,NaN,NaN,NaN,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,unknown,unknown,unknown,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Software Engineer,7.5,3.0,Normal Weight,130/85,68.0,8000.0,None,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5
821,Male,52,Accountant,6.0,8.0,Overweight,130/85,70.0,8000.0,Insomnia,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3
822,Female,40,Nurse,8.5,3.0,Normal Weight,120/80,70.0,8000.0,None,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0
823,Male,45,Sales Representative,7.0,3.0,Normal Weight,118/76,68.0,7000.0,None,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3
824,Male,18,Manager,7.5,4.0,Normal Weight,120/80,70.0,8000.0,None,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1

In [97]:
import pandas as pd
import numpy as np

s1_copy = s1.copy()


mapping_dict = {}

for index, row in s1_copy.iterrows():
    sleep_efficiency = row['sleep_efficiency']
    awakenings = row['awakenings']
    
    
    if not pd.isna(awakenings):
        if sleep_efficiency in mapping_dict:
            
            mapping_dict[sleep_efficiency].append(awakenings)
        else:
            
            mapping_dict[sleep_efficiency] = [awakenings]


def replace_nan_awakenings(row):
    sleep_efficiency = row['sleep_efficiency']
    awakenings = row['awakenings']
    
    
    if pd.isna(awakenings):
        
        if sleep_efficiency in mapping_dict:
            awakenings_options = mapping_dict[sleep_efficiency]
            awakenings = np.random.choice(awakenings_options)
        else:
            
            awakenings = np.nan
    
    return awakenings


s1_copy['awakenings'] = s1_copy.apply(replace_nan_awakenings, axis=1)

print(s1_copy)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           3.0
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1    Normal Weight         125/80        75.0      10000.0           None
2    Normal Weight         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight         130/85        68.0       8000.0           None
821     Overweight         130/85        70.0       8000.0       Insomnia
822  Normal Weight         120/80        70.0       8000.0           None
823  Normal Weight         118/76        68.0       7000.0           None
824  Normal Weight         120/80        70.0       8000.0           None

     sleep_efficiency rem_sleep_percentage deep_sleep_percentage  \
0                0.80            26.666667             57.142857
1                0.80            24.778761             57.522124
2                0.80            25.925926             55.555556
3                0.40              unknown               unknown
4                0.40              unknown               unknown
..                ...                  ...                   ...
820              0.91                 22.0                  57.0
821              0.74                 28.0                  57.0
822              0.55                 20.0                  32.0
823              0.76                 18.0                  72.0
824              0.63                 22.0                  23.0

    light_sleep_percentage  awakenings  caffeine_consumption  \
0                16.190476         2.0                   NaN
1                17.699115         4.0                   NaN
2                18.518519         2.0                   NaN
3                  unknown         NaN                   NaN
4                  unknown         NaN                   NaN
..                     ...         ...                   ...
820                   21.0         0.0                   0.0
821                   15.0         4.0                  25.0
822                   48.0         1.0                  23.0
823                   10.0         3.0                   0.0
824                   55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    NaN            NaN                   5
1                    NaN            NaN                   5
2                    NaN            NaN                   5
3                    NaN            NaN                   5
4                    NaN            NaN                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [98]:
s1 = pd.DataFrame(s1_copy)
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,26.666667,57.142857,16.190476,2.0,NaN,NaN,NaN,5
1,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,24.778761,57.522124,17.699115,4.0,NaN,NaN,NaN,5
2,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,25.925926,55.555556,18.518519,2.0,NaN,NaN,NaN,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,unknown,unknown,unknown,NaN,NaN,NaN,NaN,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,unknown,unknown,unknown,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Software Engineer,7.5,3.0,Normal Weight,130/85,68.0,8000.0,None,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5
821,Male,52,Accountant,6.0,8.0,Overweight,130/85,70.0,8000.0,Insomnia,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3
822,Female,40,Nurse,8.5,3.0,Normal Weight,120/80,70.0,8000.0,None,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0
823,Male,45,Sales Representative,7.0,3.0,Normal Weight,118/76,68.0,7000.0,None,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3
824,Male,18,Manager,7.5,4.0,Normal Weight,120/80,70.0,8000.0,None,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1

In [99]:
import pandas as pd
import numpy as np

s1_copy = s1.copy()


mapping_dict = {}

for index, row in s1_copy.iterrows():
    sleep_efficiency = row['sleep_efficiency']
    caffeine_consumption = row['caffeine_consumption']
    
    
    if not pd.isna(caffeine_consumption):
        if sleep_efficiency in mapping_dict:
            
            mapping_dict[sleep_efficiency].append(caffeine_consumption)
        else:
            
            mapping_dict[sleep_efficiency] = [caffeine_consumption]


def replace_nan_caffeine_consumption(row):
    sleep_efficiency = row['sleep_efficiency']
    caffeine_consumption = row['caffeine_consumption']
    
    
    if pd.isna(caffeine_consumption):
        
        if sleep_efficiency in mapping_dict:
            caffeine_consumption_options = mapping_dict[sleep_efficiency]
            caffeine_consumption = np.random.choice(caffeine_consumption_options)
        else:
            
            caffeine_consumption = np.nan
    
    return caffeine_consumption


s1_copy['caffeine_consumption'] = s1_copy.apply(replace_nan_caffeine_consumption, axis=1)

print(s1_copy)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           3.0
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1    Normal Weight         125/80        75.0      10000.0           None
2    Normal Weight         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight         130/85        68.0       8000.0           None
821     Overweight         130/85        70.0       8000.0       Insomnia
822  Normal Weight         120/80        70.0       8000.0           None
823  Normal Weight         118/76        68.0       7000.0           None
824  Normal Weight         120/80        70.0       8000.0           None

     sleep_efficiency rem_sleep_percentage deep_sleep_percentage  \
0                0.80            26.666667             57.142857
1                0.80            24.778761             57.522124
2                0.80            25.925926             55.555556
3                0.40              unknown               unknown
4                0.40              unknown               unknown
..                ...                  ...                   ...
820              0.91                 22.0                  57.0
821              0.74                 28.0                  57.0
822              0.55                 20.0                  32.0
823              0.76                 18.0                  72.0
824              0.63                 22.0                  23.0

    light_sleep_percentage  awakenings  caffeine_consumption  \
0                16.190476         2.0                  50.0
1                17.699115         4.0                  75.0
2                18.518519         2.0                  25.0
3                  unknown         NaN                   NaN
4                  unknown         NaN                   NaN
..                     ...         ...                   ...
820                   21.0         0.0                   0.0
821                   15.0         4.0                  25.0
822                   48.0         1.0                  23.0
823                   10.0         3.0                   0.0
824                   55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    NaN            NaN                   5
1                    NaN            NaN                   5
2                    NaN            NaN                   5
3                    NaN            NaN                   5
4                    NaN            NaN                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [100]:
s1 = pd.DataFrame(s1_copy)
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,26.666667,57.142857,16.190476,2.0,50.0,NaN,NaN,5
1,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,24.778761,57.522124,17.699115,4.0,75.0,NaN,NaN,5
2,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,25.925926,55.555556,18.518519,2.0,25.0,NaN,NaN,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,unknown,unknown,unknown,NaN,NaN,NaN,NaN,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,unknown,unknown,unknown,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Software Engineer,7.5,3.0,Normal Weight,130/85,68.0,8000.0,None,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5
821,Male,52,Accountant,6.0,8.0,Overweight,130/85,70.0,8000.0,Insomnia,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3
822,Female,40,Nurse,8.5,3.0,Normal Weight,120/80,70.0,8000.0,None,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0
823,Male,45,Sales Representative,7.0,3.0,Normal Weight,118/76,68.0,7000.0,None,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3
824,Male,18,Manager,7.5,4.0,Normal Weight,120/80,70.0,8000.0,None,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1

In [101]:
import pandas as pd
import numpy as np

s1_copy = s1.copy()


mapping_dict = {}

for index, row in s1_copy.iterrows():
    sleep_efficiency = row['sleep_efficiency']
    alcohol_consumption = row['alcohol_consumption']
    
    
    if not pd.isna(alcohol_consumption):
        if sleep_efficiency in mapping_dict:
            
            mapping_dict[sleep_efficiency].append(alcohol_consumption)
        else:
            
            mapping_dict[sleep_efficiency] = [alcohol_consumption]


def replace_nan_alcohol_consumption(row):
    sleep_efficiency = row['sleep_efficiency']
    alcohol_consumption = row['alcohol_consumption']
    
    
    if pd.isna(alcohol_consumption):
        
        if sleep_efficiency in mapping_dict:
            alcohol_consumption_options = mapping_dict[sleep_efficiency]
            alcohol_consumption = np.random.choice(alcohol_consumption_options)
        else:
            
            alcohol_consumption = np.nan
    
    return alcohol_consumption


s1_copy['alcohol_consumption'] = s1_copy.apply(replace_nan_alcohol_consumption, axis=1)

print(s1_copy)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           3.0
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1    Normal Weight         125/80        75.0      10000.0           None
2    Normal Weight         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight         130/85        68.0       8000.0           None
821     Overweight         130/85        70.0       8000.0       Insomnia
822  Normal Weight         120/80        70.0       8000.0           None
823  Normal Weight         118/76        68.0       7000.0           None
824  Normal Weight         120/80        70.0       8000.0           None

     sleep_efficiency rem_sleep_percentage deep_sleep_percentage  \
0                0.80            26.666667             57.142857
1                0.80            24.778761             57.522124
2                0.80            25.925926             55.555556
3                0.40              unknown               unknown
4                0.40              unknown               unknown
..                ...                  ...                   ...
820              0.91                 22.0                  57.0
821              0.74                 28.0                  57.0
822              0.55                 20.0                  32.0
823              0.76                 18.0                  72.0
824              0.63                 22.0                  23.0

    light_sleep_percentage  awakenings  caffeine_consumption  \
0                16.190476         2.0                  50.0
1                17.699115         4.0                  75.0
2                18.518519         2.0                  25.0
3                  unknown         NaN                   NaN
4                  unknown         NaN                   NaN
..                     ...         ...                   ...
820                   21.0         0.0                   0.0
821                   15.0         4.0                  25.0
822                   48.0         1.0                  23.0
823                   10.0         3.0                   0.0
824                   55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    0.0            NaN                   5
1                    0.0            NaN                   5
2                    0.0            NaN                   5
3                    NaN            NaN                   5
4                    NaN            NaN                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [102]:
s1 = pd.DataFrame(s1_copy)
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,26.666667,57.142857,16.190476,2.0,50.0,0.0,NaN,5
1,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,24.778761,57.522124,17.699115,4.0,75.0,0.0,NaN,5
2,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,25.925926,55.555556,18.518519,2.0,25.0,0.0,NaN,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,unknown,unknown,unknown,NaN,NaN,NaN,NaN,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,unknown,unknown,unknown,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Software Engineer,7.5,3.0,Normal Weight,130/85,68.0,8000.0,None,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5
821,Male,52,Accountant,6.0,8.0,Overweight,130/85,70.0,8000.0,Insomnia,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3
822,Female,40,Nurse,8.5,3.0,Normal Weight,120/80,70.0,8000.0,None,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0
823,Male,45,Sales Representative,7.0,3.0,Normal Weight,118/76,68.0,7000.0,None,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3
824,Male,18,Manager,7.5,4.0,Normal Weight,120/80,70.0,8000.0,None,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1

In [104]:
import pandas as pd
import numpy as np

s1_copy = s1.copy()


mapping_dict = {}

for index, row in s1_copy.iterrows():
    sleep_efficiency = row['sleep_efficiency']
    smoking_status = row['smoking_status']
    
    
    if not pd.isna(smoking_status):
        if sleep_efficiency in mapping_dict:
            
            mapping_dict[sleep_efficiency].append(smoking_status)
        else:
            
            mapping_dict[sleep_efficiency] = [smoking_status]


def replace_nan_smoking_status(row):
    sleep_efficiency = row['sleep_efficiency']
    smoking_status = row['smoking_status']
    
    
    if pd.isna(smoking_status):
        
        if sleep_efficiency in mapping_dict:
            smoking_status_options = mapping_dict[sleep_efficiency]
            smoking_status = np.random.choice(smoking_status_options)
        else:
            
            smoking_status = np.nan
    
    return smoking_status


s1_copy['smoking_status'] = s1_copy.apply(replace_nan_smoking_status, axis=1)

print(s1_copy)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           3.0
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1    Normal Weight         125/80        75.0      10000.0           None
2    Normal Weight         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight         130/85        68.0       8000.0           None
821     Overweight         130/85        70.0       8000.0       Insomnia
822  Normal Weight         120/80        70.0       8000.0           None
823  Normal Weight         118/76        68.0       7000.0           None
824  Normal Weight         120/80        70.0       8000.0           None

     sleep_efficiency rem_sleep_percentage deep_sleep_percentage  \
0                0.80            26.666667             57.142857
1                0.80            24.778761             57.522124
2                0.80            25.925926             55.555556
3                0.40              unknown               unknown
4                0.40              unknown               unknown
..                ...                  ...                   ...
820              0.91                 22.0                  57.0
821              0.74                 28.0                  57.0
822              0.55                 20.0                  32.0
823              0.76                 18.0                  72.0
824              0.63                 22.0                  23.0

    light_sleep_percentage  awakenings  caffeine_consumption  \
0                16.190476         2.0                  50.0
1                17.699115         4.0                  75.0
2                18.518519         2.0                  25.0
3                  unknown         NaN                   NaN
4                  unknown         NaN                   NaN
..                     ...         ...                   ...
820                   21.0         0.0                   0.0
821                   15.0         4.0                  25.0
822                   48.0         1.0                  23.0
823                   10.0         3.0                   0.0
824                   55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    0.0             No                   5
1                    0.0            Yes                   5
2                    0.0             No                   5
3                    NaN            NaN                   5
4                    NaN            NaN                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [105]:
s1 = pd.DataFrame(s1_copy)
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,26.666667,57.142857,16.190476,2.0,50.0,0.0,No,5
1,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,24.778761,57.522124,17.699115,4.0,75.0,0.0,Yes,5
2,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,25.925926,55.555556,18.518519,2.0,25.0,0.0,No,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,unknown,unknown,unknown,NaN,NaN,NaN,NaN,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,unknown,unknown,unknown,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Software Engineer,7.5,3.0,Normal Weight,130/85,68.0,8000.0,None,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5
821,Male,52,Accountant,6.0,8.0,Overweight,130/85,70.0,8000.0,Insomnia,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3
822,Female,40,Nurse,8.5,3.0,Normal Weight,120/80,70.0,8000.0,None,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0
823,Male,45,Sales Representative,7.0,3.0,Normal Weight,118/76,68.0,7000.0,None,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3
824,Male,18,Manager,7.5,4.0,Normal Weight,120/80,70.0,8000.0,None,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1

In [106]:
s1.isna().sum()

gender                      0
age                         0
occupation                  0
sleep_duration              0
stress_level                0
bmi_category                0
blood_pressure              0
heart_rate                  0
daily_steps                 0
sleep_disorder              0
sleep_efficiency            0
rem_sleep_percentage        0
deep_sleep_percentage       0
light_sleep_percentage      0
awakenings                268
caffeine_consumption      268
alcohol_consumption       268
smoking_status            268
exercise_frequency          0
dtype: int64

In [108]:
import pandas as pd

# Supongamos que tienes un DataFrame llamado 's1' con las columnas mencionadas

# Obtener la moda de cada columna
awakenings_mode = s1['awakenings'].mode()[0]
caffeine_mode = s1['caffeine_consumption'].mode()[0]
alcohol_mode = s1['alcohol_consumption'].mode()[0]
smoking_mode = s1['smoking_status'].mode()[0]

# Sustituir NaN por la moda en cada columna
s1['awakenings'].fillna(awakenings_mode, inplace=True)
s1['caffeine_consumption'].fillna(caffeine_mode, inplace=True)
s1['alcohol_consumption'].fillna(alcohol_mode, inplace=True)
s1['smoking_status'].fillna(smoking_mode, inplace=True)

# Mostrar el DataFrame resultante
print(s1)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           3.0
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1    Normal Weight         125/80        75.0      10000.0           None
2    Normal Weight         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight         130/85        68.0       8000.0           None
821     Overweight         130/85        70.0       8000.0       Insomnia
822  Normal Weight         120/80        70.0       8000.0           None
823  Normal Weight         118/76        68.0       7000.0           None
824  Normal Weight         120/80        70.0       8000.0           None

     sleep_efficiency rem_sleep_percentage deep_sleep_percentage  \
0                0.80            26.666667             57.142857
1                0.80            24.778761             57.522124
2                0.80            25.925926             55.555556
3                0.40              unknown               unknown
4                0.40              unknown               unknown
..                ...                  ...                   ...
820              0.91                 22.0                  57.0
821              0.74                 28.0                  57.0
822              0.55                 20.0                  32.0
823              0.76                 18.0                  72.0
824              0.63                 22.0                  23.0

    light_sleep_percentage  awakenings  caffeine_consumption  \
0                16.190476         2.0                  50.0
1                17.699115         4.0                  75.0
2                18.518519         2.0                  25.0
3                  unknown         1.0                   0.0
4                  unknown         1.0                   0.0
..                     ...         ...                   ...
820                   21.0         0.0                   0.0
821                   15.0         4.0                  25.0
822                   48.0         1.0                  23.0
823                   10.0         3.0                   0.0
824                   55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    0.0             No                   5
1                    0.0            Yes                   5
2                    0.0             No                   5
3                    0.0             No                   5
4                    0.0             No                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [109]:
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,26.666667,57.142857,16.190476,2.0,50.0,0.0,No,5
1,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,24.778761,57.522124,17.699115,4.0,75.0,0.0,Yes,5
2,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,25.925926,55.555556,18.518519,2.0,25.0,0.0,No,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,unknown,unknown,unknown,1.0,0.0,0.0,No,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,unknown,unknown,unknown,1.0,0.0,0.0,No,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Software Engineer,7.5,3.0,Normal Weight,130/85,68.0,8000.0,None,0.91,22.0,57.0,21.0,0.0,0.0,0.0,No,5
821,Male,52,Accountant,6.0,8.0,Overweight,130/85,70.0,8000.0,Insomnia,0.74,28.0,57.0,15.0,4.0,25.0,0.0,No,3
822,Female,40,Nurse,8.5,3.0,Normal Weight,120/80,70.0,8000.0,None,0.55,20.0,32.0,48.0,1.0,23.0,3.0,Yes,0
823,Male,45,Sales Representative,7.0,3.0,Normal Weight,118/76,68.0,7000.0,None,0.76,18.0,72.0,10.0,3.0,0.0,0.0,No,3
824,Male,18,Manager,7.5,4.0,Normal Weight,120/80,70.0,8000.0,None,0.63,22.0,23.0,55.0,1.0,50.0,0.0,No,1

In [114]:
import pandas as pd
import numpy as np

s1['rem_sleep_percentage'] = s1['rem_sleep_percentage'].replace('unknown', np.nan)

s1['rem_sleep_percentage'] = pd.to_numeric(s1['rem_sleep_percentage'], errors='coerce')

media_columna = s1['rem_sleep_percentage'].mean()

s1['rem_sleep_percentage'].fillna(media_columna, inplace=True)

print(s1)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           3.0
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1    Normal Weight         125/80        75.0      10000.0           None
2    Normal Weight         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight         130/85        68.0       8000.0           None
821     Overweight         130/85        70.0       8000.0       Insomnia
822  Normal Weight         120/80        70.0       8000.0           None
823  Normal Weight         118/76        68.0       7000.0           None
824  Normal Weight         120/80        70.0       8000.0           None

     sleep_efficiency  rem_sleep_percentage deep_sleep_percentage  \
0                0.80             26.000000             57.142857
1                0.80             24.000000             57.522124
2                0.80             25.000000             55.555556
3                0.40             22.472172               unknown
4                0.40             22.472172               unknown
..                ...                   ...                   ...
820              0.91             22.000000                  57.0
821              0.74             28.000000                  57.0
822              0.55             20.000000                  32.0
823              0.76             18.000000                  72.0
824              0.63             22.000000                  23.0

    light_sleep_percentage  awakenings  caffeine_consumption  \
0                16.190476         2.0                  50.0
1                17.699115         4.0                  75.0
2                18.518519         2.0                  25.0
3                  unknown         1.0                   0.0
4                  unknown         1.0                   0.0
..                     ...         ...                   ...
820                   21.0         0.0                   0.0
821                   15.0         4.0                  25.0
822                   48.0         1.0                  23.0
823                   10.0         3.0                   0.0
824                   55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    0.0             No                   5
1                    0.0            Yes                   5
2                    0.0             No                   5
3                    0.0             No                   5
4                    0.0             No                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [115]:
import pandas as pd
import numpy as np

s1['deep_sleep_percentage'] = s1['deep_sleep_percentage'].replace('deep_sleep_percentage', np.nan)

s1['deep_sleep_percentage'] = pd.to_numeric(s1['deep_sleep_percentage'], errors='coerce')

media_columna = s1['deep_sleep_percentage'].mean()

s1['deep_sleep_percentage'].fillna(media_columna, inplace=True)

print(s1)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           3.0
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1    Normal Weight         125/80        75.0      10000.0           None
2    Normal Weight         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight         130/85        68.0       8000.0           None
821     Overweight         130/85        70.0       8000.0       Insomnia
822  Normal Weight         120/80        70.0       8000.0           None
823  Normal Weight         118/76        68.0       7000.0           None
824  Normal Weight         120/80        70.0       8000.0           None

     sleep_efficiency  rem_sleep_percentage  deep_sleep_percentage  \
0                0.80             26.000000              57.142857
1                0.80             24.000000              57.522124
2                0.80             25.000000              55.555556
3                0.40             22.472172              54.576192
4                0.40             22.472172              54.576192
..                ...                   ...                    ...
820              0.91             22.000000              57.000000
821              0.74             28.000000              57.000000
822              0.55             20.000000              32.000000
823              0.76             18.000000              72.000000
824              0.63             22.000000              23.000000

    light_sleep_percentage  awakenings  caffeine_consumption  \
0                16.190476         2.0                  50.0
1                17.699115         4.0                  75.0
2                18.518519         2.0                  25.0
3                  unknown         1.0                   0.0
4                  unknown         1.0                   0.0
..                     ...         ...                   ...
820                   21.0         0.0                   0.0
821                   15.0         4.0                  25.0
822                   48.0         1.0                  23.0
823                   10.0         3.0                   0.0
824                   55.0         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    0.0             No                   5
1                    0.0            Yes                   5
2                    0.0             No                   5
3                    0.0             No                   5
4                    0.0             No                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [116]:
import pandas as pd
import numpy as np

s1['light_sleep_percentage'] = s1['light_sleep_percentage'].replace('light_sleep_percentage', np.nan)

s1['light_sleep_percentage'] = pd.to_numeric(s1['light_sleep_percentage'], errors='coerce')

media_columna = s1['light_sleep_percentage'].mean()

s1['light_sleep_percentage'].fillna(media_columna, inplace=True)

print(s1)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           3.0
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1    Normal Weight         125/80        75.0      10000.0           None
2    Normal Weight         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight         130/85        68.0       8000.0           None
821     Overweight         130/85        70.0       8000.0       Insomnia
822  Normal Weight         120/80        70.0       8000.0           None
823  Normal Weight         118/76        68.0       7000.0           None
824  Normal Weight         120/80        70.0       8000.0           None

     sleep_efficiency  rem_sleep_percentage  deep_sleep_percentage  \
0                0.80             26.000000              57.142857
1                0.80             24.000000              57.522124
2                0.80             25.000000              55.555556
3                0.40             22.472172              54.576192
4                0.40             22.472172              54.576192
..                ...                   ...                    ...
820              0.91             22.000000              57.000000
821              0.74             28.000000              57.000000
822              0.55             20.000000              32.000000
823              0.76             18.000000              72.000000
824              0.63             22.000000              23.000000

     light_sleep_percentage  awakenings  caffeine_consumption  \
0                 16.190476         2.0                  50.0
1                 17.699115         4.0                  75.0
2                 18.518519         2.0                  25.0
3                 22.866574         1.0                   0.0
4                 22.866574         1.0                   0.0
..                      ...         ...                   ...
820               21.000000         0.0                   0.0
821               15.000000         4.0                  25.0
822               48.000000         1.0                  23.0
823               10.000000         3.0                   0.0
824               55.000000         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    0.0             No                   5
1                    0.0            Yes                   5
2                    0.0             No                   5
3                    0.0             No                   5
4                    0.0             No                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [117]:
import pandas as pd

s1['rem_sleep_percentage'] = s1['rem_sleep_percentage'].round(2)
s1['deep_sleep_percentage'] = s1['deep_sleep_percentage'].round(2)
s1['light_sleep_percentage'] = s1['light_sleep_percentage'].round(2)

print(s1)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27     Software Engineer             7.5           3.0
821    Male   52            Accountant             6.0           8.0
822  Female   40                 Nurse             8.5           3.0
823    Male   45  Sales Representative             7.0           3.0
824    Male   18               Manager             7.5           4.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0           None
1    Normal Weight         125/80        75.0      10000.0           None
2    Normal Weight         125/80        75.0      10000.0           None
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820  Normal Weight         130/85        68.0       8000.0           None
821     Overweight         130/85        70.0       8000.0       Insomnia
822  Normal Weight         120/80        70.0       8000.0           None
823  Normal Weight         118/76        68.0       7000.0           None
824  Normal Weight         120/80        70.0       8000.0           None

     sleep_efficiency  rem_sleep_percentage  deep_sleep_percentage  \
0                0.80                 26.00                  57.14
1                0.80                 24.00                  57.52
2                0.80                 25.00                  55.56
3                0.40                 22.47                  54.58
4                0.40                 22.47                  54.58
..                ...                   ...                    ...
820              0.91                 22.00                  57.00
821              0.74                 28.00                  57.00
822              0.55                 20.00                  32.00
823              0.76                 18.00                  72.00
824              0.63                 22.00                  23.00

     light_sleep_percentage  awakenings  caffeine_consumption  \
0                     16.19         2.0                  50.0
1                     17.70         4.0                  75.0
2                     18.52         2.0                  25.0
3                     22.87         1.0                   0.0
4                     22.87         1.0                   0.0
..                      ...         ...                   ...
820                   21.00         0.0                   0.0
821                   15.00         4.0                  25.0
822                   48.00         1.0                  23.0
823                   10.00         3.0                   0.0
824                   55.00         1.0                  50.0

     alcohol_consumption smoking_status  exercise_frequency
0                    0.0             No                   5
1                    0.0            Yes                   5
2                    0.0             No                   5
3                    0.0             No                   5
4                    0.0             No                   5
..                   ...            ...                 ...
820                  0.0             No                   5
821                  0.0             No                   3
822                  3.0            Yes                   0
823                  0.0             No                   3
824                  0.0             No                   1

[825 rows x 19 columns]

In [118]:
s1

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,None,0.80,26.00,57.14,16.19,2.0,50.0,0.0,No,5
1,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,24.00,57.52,17.70,4.0,75.0,0.0,Yes,5
2,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,None,0.80,25.00,55.56,18.52,2.0,25.0,0.0,No,5
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,22.47,54.58,22.87,1.0,0.0,0.0,No,5
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,22.47,54.58,22.87,1.0,0.0,0.0,No,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Software Engineer,7.5,3.0,Normal Weight,130/85,68.0,8000.0,None,0.91,22.00,57.00,21.00,0.0,0.0,0.0,No,5
821,Male,52,Accountant,6.0,8.0,Overweight,130/85,70.0,8000.0,Insomnia,0.74,28.00,57.00,15.00,4.0,25.0,0.0,No,3
822,Female,40,Nurse,8.5,3.0,Normal Weight,120/80,70.0,8000.0,None,0.55,20.00,32.00,48.00,1.0,23.0,3.0,Yes,0
823,Male,45,Sales Representative,7.0,3.0,Normal Weight,118/76,68.0,7000.0,None,0.76,18.00,72.00,10.00,3.0,0.0,0.0,No,3
824,Male,18,Manager,7.5,4.0,Normal Weight,120/80,70.0,8000.0,None,0.63,22.00,23.00,55.00,1.0,50.0,0.0,No,1

In [121]:
s1.to_csv('s1.csv', index=False)