In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pylab as plt
from scipy.stats import f_oneway, norm, f, chi2, chi2_contingency
import statsmodels.api as sm
from statsmodels.formula.api import ols
import warnings
warnings.simplefilter('ignore')
from scipy.stats import ttest_ind 
from statsmodels.multivariate.manova import MANOVA

In [2]:
%ls

 El volumen de la unidad C es Local Disk
 El número de serie del volumen es: 0671-FAEA

 Directorio de C:\Users\Monica\proyecto

21/02/2024  09:27    <DIR>          .
21/02/2024  09:27    <DIR>          ..
21/02/2024  09:21    <DIR>          .ipynb_checkpoints
20/02/2024  16:28             1.273 gb_dur.csv
20/02/2024  16:27             2.240 gb_eff.csv
02/02/2024  10:24    <DIR>          Graficas_Sleep_Github
20/02/2024  15:18    <DIR>          groupby
02/02/2024  11:35         2.577.782 Habitos del sueño.pptx
01/02/2024  19:54           608.729 Project Sleep Efficiency.ipynb
29/01/2024  17:25                10 README.md
01/02/2024  19:52            87.267 s1.csv
21/02/2024  09:21           193.291 sleep project 2.ipynb
30/01/2024  16:37            41.369 Sleep_Efficiency.csv
19/02/2024  13:07            89.240 sleep_project2.csv
20/02/2024  19:07           106.153 sleep_project3.csv
30/01/2024  13:21            24.072 ss.csv
19/02/2024  13:08           832.485 Tabla clean, graficas explicativas.ipynb
21/02/2024  09:27             3.708 Untitled.ipynb
              13 archivos      4.567.619 bytes
               5 dirs  134.943.395.840 bytes libres

In [3]:
sleep_project2 = pd.read_csv('sleep_project2.csv')
sleep_project2

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,NaN,0.80,28.57,56.12,15.31,2.0,No,No,Yes,Si
1,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,Insomnia,0.80,19.15,63.83,17.02,3.0,Si,No,Yes,Si
2,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,Insomnia,0.80,26.67,57.14,16.19,1.0,No,No,No,Si
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,22.53,54.53,22.94,1.0,No,No,No,Si
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,22.53,54.53,22.94,1.0,No,No,No,Si
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Salesperson,7.5,3.0,Overweight,140/95,68.0,10000.0,Sleep Apnea,0.91,22.00,57.00,21.00,0.0,No,No,No,Si
821,Male,52,Scientist,6.0,8.0,Normal Weight,125/80,65.0,5000.0,Insomnia,0.74,28.00,57.00,15.00,4.0,Si,No,No,Si
822,Female,40,Doctor,8.5,3.0,Normal Weight,120/80,70.0,8000.0,Sleep Apnea,0.55,20.00,32.00,48.00,1.0,Si,Si,Yes,No
823,Male,45,Scientist,7.0,3.0,Overweight,130/85,70.0,6000.0,Insomnia,0.76,18.00,72.00,10.00,3.0,No,No,No,Si
824,Male,18,Doctor,7.5,5.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.63,22.00,23.00,55.00,1.0,Si,No,No,Si

In [4]:


# Definir el mapeo de edades a generaciones
generations_mapping = {
    (0, 25): 'Generacion Z',
    (26, 40): 'Millennials',
    (41, 56): 'Generacion X',
    (57, 75): 'Baby Boomers'
}

# Función para asignar la generación según la edad
def assign_generation(age):
    for age_range, generation in generations_mapping.items():
        if age_range[0] <= age <= age_range[1]:
            return generation
    return 'Otra'

# Aplicar la función a la columna 'age' para obtener la columna 'generation'
sleep_project2['generation'] = sleep_project2['age'].apply(assign_generation)

# Mostrar el DataFrame con la nueva columna 'generation'
print(sleep_project2)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27           Salesperson             7.5           3.0
821    Male   52             Scientist             6.0           8.0
822  Female   40                Doctor             8.5           3.0
823    Male   45             Scientist             7.0           3.0
824    Male   18                Doctor             7.5           5.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0            NaN
1    Normal Weight         125/80        75.0      10000.0       Insomnia
2    Normal Weight         125/80        75.0      10000.0       Insomnia
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820     Overweight         140/95        68.0      10000.0    Sleep Apnea
821  Normal Weight         125/80        65.0       5000.0       Insomnia
822  Normal Weight         120/80        70.0       8000.0    Sleep Apnea
823     Overweight         130/85        70.0       6000.0       Insomnia
824          Obese         140/90        85.0       3000.0    Sleep Apnea

     sleep_efficiency  rem_sleep_percentage  deep_sleep_percentage  \
0                0.80                 28.57                  56.12
1                0.80                 19.15                  63.83
2                0.80                 26.67                  57.14
3                0.40                 22.53                  54.53
4                0.40                 22.53                  54.53
..                ...                   ...                    ...
820              0.91                 22.00                  57.00
821              0.74                 28.00                  57.00
822              0.55                 20.00                  32.00
823              0.76                 18.00                  72.00
824              0.63                 22.00                  23.00

     light_sleep_percentage  awakenings caffeine_consumption  \
0                     15.31         2.0                   No
1                     17.02         3.0                   Si
2                     16.19         1.0                   No
3                     22.94         1.0                   No
4                     22.94         1.0                   No
..                      ...         ...                  ...
820                   21.00         0.0                   No
821                   15.00         4.0                   Si
822                   48.00         1.0                   Si
823                   10.00         3.0                   No
824                   55.00         1.0                   Si

    alcohol_consumption smoking_status exercise_frequency    generation
0                    No            Yes                 Si   Millennials
1                    No            Yes                 Si   Millennials
2                    No             No                 Si   Millennials
3                    No             No                 Si   Millennials
4                    No             No                 Si   Millennials
..                  ...            ...                ...           ...
820                  No             No                 Si   Millennials
821                  No             No                 Si  Generacion X
822                  Si            Yes                 No   Millennials
823                  No             No                 Si  Generacion X
824                  No             No                 Si  Generacion Z

[825 rows x 20 columns]

In [5]:
sleep_project2

,gender,age,occupation,sleep_duration,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,sleep_efficiency,rem_sleep_percentage,deep_sleep_percentage,light_sleep_percentage,awakenings,caffeine_consumption,alcohol_consumption,smoking_status,exercise_frequency,generation
0,Male,27,Software Engineer,6.1,6.0,Overweight,126/83,77.0,4200.0,NaN,0.80,28.57,56.12,15.31,2.0,No,No,Yes,Si,Millennials
1,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,Insomnia,0.80,19.15,63.83,17.02,3.0,Si,No,Yes,Si,Millennials
2,Male,28,Doctor,6.2,8.0,Normal Weight,125/80,75.0,10000.0,Insomnia,0.80,26.67,57.14,16.19,1.0,No,No,No,Si,Millennials
3,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,22.53,54.53,22.94,1.0,No,No,No,Si,Millennials
4,Male,28,Sales Representative,5.9,8.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.40,22.53,54.53,22.94,1.0,No,No,No,Si,Millennials
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Female,27,Salesperson,7.5,3.0,Overweight,140/95,68.0,10000.0,Sleep Apnea,0.91,22.00,57.00,21.00,0.0,No,No,No,Si,Millennials
821,Male,52,Scientist,6.0,8.0,Normal Weight,125/80,65.0,5000.0,Insomnia,0.74,28.00,57.00,15.00,4.0,Si,No,No,Si,Generacion X
822,Female,40,Doctor,8.5,3.0,Normal Weight,120/80,70.0,8000.0,Sleep Apnea,0.55,20.00,32.00,48.00,1.0,Si,Si,Yes,No,Millennials
823,Male,45,Scientist,7.0,3.0,Overweight,130/85,70.0,6000.0,Insomnia,0.76,18.00,72.00,10.00,3.0,No,No,No,Si,Generacion X
824,Male,18,Doctor,7.5,5.0,Obese,140/90,85.0,3000.0,Sleep Apnea,0.63,22.00,23.00,55.00,1.0,Si,No,No,Si,Generacion Z

In [6]:
sleep_project2.sleep_disorder.unique()

array([nan, 'Insomnia', 'Sleep Apnea'], dtype=object)

In [7]:
# Reemplazar los NaN en la columna 'sleep_disorder' por 'unknown'
sleep_project2['sleep_disorder'].fillna('unknown', inplace=True)

# Mostrar el DataFrame actualizado
print(sleep_project2)

     gender  age            occupation  sleep_duration  stress_level  \
0      Male   27     Software Engineer             6.1           6.0
1      Male   28                Doctor             6.2           8.0
2      Male   28                Doctor             6.2           8.0
3      Male   28  Sales Representative             5.9           8.0
4      Male   28  Sales Representative             5.9           8.0
..      ...  ...                   ...             ...           ...
820  Female   27           Salesperson             7.5           3.0
821    Male   52             Scientist             6.0           8.0
822  Female   40                Doctor             8.5           3.0
823    Male   45             Scientist             7.0           3.0
824    Male   18                Doctor             7.5           5.0

      bmi_category blood_pressure  heart_rate  daily_steps sleep_disorder  \
0       Overweight         126/83        77.0       4200.0        unknown
1    Normal Weight         125/80        75.0      10000.0       Insomnia
2    Normal Weight         125/80        75.0      10000.0       Insomnia
3            Obese         140/90        85.0       3000.0    Sleep Apnea
4            Obese         140/90        85.0       3000.0    Sleep Apnea
..             ...            ...         ...          ...            ...
820     Overweight         140/95        68.0      10000.0    Sleep Apnea
821  Normal Weight         125/80        65.0       5000.0       Insomnia
822  Normal Weight         120/80        70.0       8000.0    Sleep Apnea
823     Overweight         130/85        70.0       6000.0       Insomnia
824          Obese         140/90        85.0       3000.0    Sleep Apnea

     sleep_efficiency  rem_sleep_percentage  deep_sleep_percentage  \
0                0.80                 28.57                  56.12
1                0.80                 19.15                  63.83
2                0.80                 26.67                  57.14
3                0.40                 22.53                  54.53
4                0.40                 22.53                  54.53
..                ...                   ...                    ...
820              0.91                 22.00                  57.00
821              0.74                 28.00                  57.00
822              0.55                 20.00                  32.00
823              0.76                 18.00                  72.00
824              0.63                 22.00                  23.00

     light_sleep_percentage  awakenings caffeine_consumption  \
0                     15.31         2.0                   No
1                     17.02         3.0                   Si
2                     16.19         1.0                   No
3                     22.94         1.0                   No
4                     22.94         1.0                   No
..                      ...         ...                  ...
820                   21.00         0.0                   No
821                   15.00         4.0                   Si
822                   48.00         1.0                   Si
823                   10.00         3.0                   No
824                   55.00         1.0                   Si

    alcohol_consumption smoking_status exercise_frequency    generation
0                    No            Yes                 Si   Millennials
1                    No            Yes                 Si   Millennials
2                    No             No                 Si   Millennials
3                    No             No                 Si   Millennials
4                    No             No                 Si   Millennials
..                  ...            ...                ...           ...
820                  No             No                 Si   Millennials
821                  No             No                 Si  Generacion X
822                  Si            Yes                 No   Millennials
823                  No             No                 Si  Generacion X
824                  No             No                 Si  Generacion Z

[825 rows x 20 columns]

In [8]:
sleep_project2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   gender                  825 non-null    object
 1   age                     825 non-null    int64
 2   occupation              825 non-null    object
 3   sleep_duration          825 non-null    float64
 4   stress_level            825 non-null    float64
 5   bmi_category            825 non-null    object
 6   blood_pressure          825 non-null    object
 7   heart_rate              825 non-null    float64
 8   daily_steps             825 non-null    float64
 9   sleep_disorder          825 non-null    object
 10  sleep_efficiency        825 non-null    float64
 11  rem_sleep_percentage    825 non-null    float64
 12  deep_sleep_percentage   825 non-null    float64
 13  light_sleep_percentage  825 non-null    float64
 14  awakenings              825 non-null    float64
 15  caffeine_consumption    825 non-null    object
 16  alcohol_consumption     825 non-null    object
 17  smoking_status          825 non-null    object
 18  exercise_frequency      825 non-null    object
 19  generation              825 non-null    object
dtypes: float64(9), int64(1), object(10)
memory usage: 129.0+ KB

In [9]:
from scipy.stats import ttest_ind

# Extraer las muestras para el test
sample1 = sleep_project2['sleep_duration']
sample2 = sleep_project2['sleep_efficiency']

# Realizar el test de hipótesis
t_statistic, p_value = ttest_ind(sample1, sample2, equal_var=False)

# Imprimir los resultados
print("Estadístico t:", t_statistic)
print("Valor p:", p_value)

# Comparar el valor p con un nivel de significancia (alfa) predefinido
alpha = 0.05
if p_value < alpha:
    print("Rechazamos la hipótesis nula (Ho) en favor de la hipótesis alternativa (H1)")
else:
    print("No hay suficiente evidencia para rechazar la hipótesis nula (Ho)")

Estadístico t: 208.35055835036093
Valor p: 0.0
Rechazamos la hipótesis nula (Ho) en favor de la hipótesis alternativa (H1)

In [10]:
gb_eff = sleep_project2[["sleep_efficiency", "age", "sleep_duration", "stress_level","awakenings", "heart_rate", "daily_steps"]]
gb_eff = gb_eff.groupby('sleep_efficiency').mean().round(2)
gb_eff

,age,sleep_duration,stress_level,awakenings,heart_rate,daily_steps
sleep_efficiency,,,,,,
0.40,30.40,5.86,8.00,1.00,83.40,3880.00
0.50,36.88,7.69,3.38,2.50,73.88,5900.00
0.51,40.50,7.00,4.25,3.00,73.38,6162.50
0.52,35.56,7.06,3.89,2.22,72.11,6533.33
0.53,40.33,7.83,3.00,2.33,70.33,7083.33
0.54,28.12,7.31,3.88,2.00,68.00,6625.00
0.55,30.14,7.79,3.14,2.43,71.57,7142.86
0.56,19.50,7.50,5.50,2.00,86.00,3700.00
0.57,27.50,7.00,3.00,3.00,72.00,7000.00
0.58,26.33,7.83,3.67,1.33,74.67,5766.67
0.59,28.00,8.50,3.00,2.50,70.00,7000.00
0.60,38.33,7.58,3.33,2.67,79.83,4833.33
0.60,32.71,6.50,7.00,1.00,77.71,4257.14
0.61,40.50,7.75,3.00,1.00,77.00,6850.00
0.62,36.25,7.50,3.00,1.75,68.25,6500.00
0.63,40.44,7.50,3.22,2.44,71.67,6277.78
0.64,43.12,6.81,5.50,2.75,72.38,6512.50
0.65,36.50,8.62,3.00,2.00,73.50,5000.00
0.66,55.43,8.29,3.00,2.71,69.14,7000.00
0.67,49.50,7.56,3.25,1.88,71.62,7187.50
0.68,41.11,7.22,3.22,2.33,69.78,6222.22
0.69,63.00,8.50,3.00,3.00,72.00,8000.00
0.70,44.00,8.00,4.00,1.67,71.00,8666.67
0.71,45.18,7.55,3.73,2.27,73.00,5527.27
0.72,40.92,7.50,3.83,2.33,72.50,6491.67
0.73,48.57,7.50,3.29,3.00,72.57,6142.86
0.74,50.75,6.38,4.50,3.00,75.75,4500.00
0.75,36.88,7.38,3.62,3.12,76.62,5787.50
0.76,45.86,7.64,3.00,3.14,69.43,7428.57
0.77,42.15,7.81,3.15,3.00,73.85,5615.38
0.78,40.33,7.94,3.56,2.11,77.22,4877.78
0.79,37.75,6.88,5.00,2.75,74.75,5912.50
0.80,40.44,6.29,7.22,2.71,73.15,6945.69
0.81,31.42,7.50,3.25,2.58,74.00,5316.67
0.82,42.45,7.55,3.27,2.55,73.00,6500.00
0.83,41.80,7.25,4.30,2.00,72.80,6150.00
0.84,37.75,7.58,3.17,2.67,73.33,6125.00
0.85,37.42,7.75,3.67,0.58,73.42,6308.33
0.86,38.92,7.25,3.00,0.67,72.00,6666.67
0.87,42.36,7.32,3.73,0.50,74.00,5636.36
0.88,39.15,7.31,3.85,0.46,73.38,6015.38
0.89,36.00,8.00,3.00,0.71,73.00,6142.86
0.90,42.28,7.28,3.69,0.55,74.41,6248.28
0.91,38.42,7.34,3.53,0.68,73.84,6110.53
0.92,40.62,7.42,4.46,0.62,70.00,7023.08
0.93,42.27,7.55,3.27,0.45,72.64,5495.45
0.94,40.67,7.33,3.50,0.44,70.50,6333.33
0.95,42.33,7.57,3.67,0.43,73.81,6123.81
0.96,44.29,7.29,3.57,0.43,70.43,7357.14
0.97,48.00,7.50,3.00,0.00,68.00,7000.00
0.98,47.50,7.75,3.00,0.25,72.25,5575.00
0.99,54.00,8.00,3.00,1.00,77.00,4200.00
1.00,38.78,7.14,5.35,1.00,69.42,6659.74
1.20,38.61,7.40,4.61,1.00,68.63,7462.39
1.40,54.76,8.25,3.03,1.00,67.14,6034.29

In [11]:
gb_dur = sleep_project2[["sleep_duration", "age", "sleep_efficiency", "stress_level","awakenings", "heart_rate", "daily_steps"]]
gb_dur = gb_dur.groupby('sleep_duration').mean().round(2)
gb_dur

,age,sleep_efficiency,stress_level,awakenings,heart_rate,daily_steps
sleep_duration,,,,,,
5.0,43.88,0.81,3.00,1.50,75.75,5712.50
5.5,54.00,0.83,3.00,0.67,69.33,6333.33
5.8,34.00,0.40,8.00,1.00,81.00,5200.00
5.9,33.00,0.50,8.00,1.75,82.50,4750.00
6.0,40.38,0.79,8.00,2.08,73.29,6710.77
6.1,41.80,0.80,7.84,2.84,73.92,7976.00
6.2,37.17,0.80,7.67,2.67,74.17,7583.33
6.3,42.77,0.80,7.00,2.38,72.77,5807.69
6.4,40.78,0.76,7.00,2.11,73.33,5577.78
6.5,42.92,0.85,6.08,2.12,70.77,5769.23
6.6,45.15,0.96,4.90,1.00,67.30,5880.00
6.7,39.80,1.00,4.40,1.00,67.00,5840.00
6.8,43.60,0.92,6.60,1.80,72.80,5400.00
6.9,42.33,0.93,6.00,1.00,73.00,5933.33
7.0,40.82,0.78,3.00,1.76,72.67,6102.60
7.1,38.58,1.17,4.53,1.00,68.63,7052.63
7.2,37.31,1.20,4.47,1.00,68.11,7211.11
7.3,38.79,1.17,4.79,1.00,69.57,6371.43
7.4,36.80,1.12,5.00,1.00,74.40,6120.00
7.5,39.32,0.82,4.10,1.40,72.67,6447.31
7.6,36.20,1.10,5.40,1.00,69.80,7880.00
7.7,35.50,1.08,5.58,1.00,70.00,8000.00
7.8,38.14,1.14,5.25,1.00,69.86,7928.57
7.9,33.00,1.09,5.43,1.00,69.29,7828.57
8.0,41.42,0.87,3.00,1.50,72.44,6233.62
8.1,56.43,1.40,3.14,1.00,71.14,6242.86
8.2,57.55,1.40,3.00,1.00,67.45,7545.45
8.3,52.40,1.40,3.00,1.00,65.00,5000.00
8.4,53.21,1.40,3.00,1.00,65.00,5000.00
8.5,42.80,0.96,3.00,1.51,71.51,5560.98
9.0,39.15,0.75,3.00,1.62,72.62,6246.15
10.0,43.12,0.76,3.00,1.62,68.00,6750.00

In [12]:
gb_gender = sleep_project2[["gender", "age", "sleep_duration", "sleep_efficiency", "stress_level","awakenings", "heart_rate", "daily_steps"]]
gb_gender = gb_gender.groupby('gender').mean().round(2)
gb_gender

,age,sleep_duration,sleep_efficiency,stress_level,awakenings,heart_rate,daily_steps
gender,,,,,,,
Female,41.69,7.38,0.94,4.05,1.43,70.96,6442.65
Male,40.57,7.25,0.88,4.75,1.68,72.37,6457.31

In [13]:
gb_age = sleep_project2[["age", "sleep_duration", "sleep_efficiency", "stress_level","awakenings", "heart_rate", "daily_steps"]]
gb_age = gb_age.groupby("age").mean().round(2)
gb_age

,sleep_duration,sleep_efficiency,stress_level,awakenings,heart_rate,daily_steps
age,,,,,,
9,8.50,0.52,3.00,2.0,68.00,7000.00
10,7.00,0.54,3.00,3.0,70.00,6000.00
11,9.00,0.55,3.00,4.0,68.00,7000.00
12,9.00,0.56,3.00,1.0,86.00,3700.00
13,8.00,0.58,3.00,1.0,70.00,8000.00
...,...,...,...,...,...,...
65,7.36,0.75,3.64,2.0,73.45,5754.55
66,7.50,0.88,3.00,0.0,84.00,3300.00
67,8.50,0.78,3.00,3.0,78.00,4100.00
68,7.50,0.74,4.00,4.0,83.00,3500.00
69,7.00,0.66,3.00,3.0,72.00,6000.00

In [14]:
gb_occup = sleep_project2[["occupation", "age", "sleep_duration", "sleep_efficiency", "stress_level","awakenings", "heart_rate", "daily_steps"]]
gb_occup = gb_occup.groupby('occupation').mean().round(2)
gb_occup

,age,sleep_duration,sleep_efficiency,stress_level,awakenings,heart_rate,daily_steps
occupation,,,,,,,
Accountant,39.96,7.25,0.95,3.99,1.41,70.95,6703.53
Doctor,34.23,7.13,0.88,5.62,1.81,72.31,6633.33
Engineer,43.27,7.71,1.09,3.94,1.31,69.85,5804.00
Lawyer,39.84,7.53,1.01,4.34,1.27,70.93,6842.68
Manager,42.59,7.64,0.78,3.65,1.57,71.27,6708.16
Nurse,47.05,7.20,0.97,4.95,1.62,72.60,7220.51
Sales Representative,40.72,7.41,0.77,3.89,1.52,75.02,5606.52
Salesperson,41.94,6.99,0.80,4.97,2.01,72.15,6168.75
Scientist,41.36,7.42,0.75,3.75,1.70,72.70,6168.18
Software Engineer,36.08,7.28,0.84,3.84,1.49,71.95,6240.54
Teacher,42.09,7.10,0.90,3.91,1.38,70.41,6078.75

In [15]:
gb_bmi = sleep_project2[["bmi_category", "age", "sleep_duration", "sleep_efficiency", "stress_level","awakenings", "heart_rate", "daily_steps"]]
gb_bmi.groupby('bmi_category').mean().round(2)

,age,sleep_duration,sleep_efficiency,stress_level,awakenings,heart_rate,daily_steps
bmi_category,,,,,,,
Normal Weight,39.58,7.44,0.96,4.29,1.43,69.14,6788.79
Obese,40.16,7.36,0.80,3.87,1.63,84.23,3350.45
Overweight,44.10,7.09,0.89,4.81,1.72,70.68,7170.15

In [16]:
gb_disorder = sleep_project2[["sleep_disorder", "age", "sleep_duration", "sleep_efficiency", "stress_level","awakenings", "heart_rate", "daily_steps"]]
gb_disorder.groupby('sleep_disorder').mean().round(2)

,age,sleep_duration,sleep_efficiency,stress_level,awakenings,heart_rate,daily_steps
sleep_disorder,,,,,,,
Insomnia,40.77,7.30,0.92,4.36,1.60,70.11,6127.49
Sleep Apnea,41.66,7.34,0.91,4.46,1.50,73.78,6873.78
unknown,39.75,7.24,0.95,4.62,1.44,71.06,6575.00

In [17]:
gb_caff = sleep_project2[["caffeine_consumption", "age", "sleep_duration", "sleep_efficiency", "stress_level","awakenings", "heart_rate", "daily_steps"]]
gb_caff.groupby("caffeine_consumption").mean().round(2)

,age,sleep_duration,sleep_efficiency,stress_level,awakenings,heart_rate,daily_steps
caffeine_consumption,,,,,,,
No,42.75,7.42,0.99,4.23,1.36,70.97,6512.83
Si,38.64,7.16,0.79,4.67,1.85,72.74,6353.99

In [18]:
gb_alc = sleep_project2[["alcohol_consumption", "age", "sleep_duration", "sleep_efficiency", "stress_level","awakenings", "heart_rate", "daily_steps"]]
gb_alc.groupby("alcohol_consumption").mean().round(2)

,age,sleep_duration,sleep_efficiency,stress_level,awakenings,heart_rate,daily_steps
alcohol_consumption,,,,,,,
No,41.11,7.29,0.98,4.61,1.41,71.26,6489.17
Si,41.16,7.37,0.74,3.87,1.94,72.76,6345.78

In [19]:
gb_smoking = sleep_project2[["smoking_status", "age", "sleep_duration", "sleep_efficiency", "stress_level","awakenings", "heart_rate", "daily_steps"]]
gb_smoking.groupby("smoking_status").mean().round(2)

,age,sleep_duration,sleep_efficiency,stress_level,awakenings,heart_rate,daily_steps
smoking_status,,,,,,,
No,41.25,7.35,0.96,4.37,1.46,71.28,6459.14
Yes,40.72,7.20,0.75,4.53,1.84,72.94,6420.92

In [20]:
gb_exer = sleep_project2[["exercise_frequency", "age", "sleep_duration", "sleep_efficiency", "stress_level","awakenings", "heart_rate", "daily_steps"]]
gb_exer.groupby("exercise_frequency").mean().round(2)

,age,sleep_duration,sleep_efficiency,stress_level,awakenings,heart_rate,daily_steps
exercise_frequency,,,,,,,
No,41.62,7.59,0.74,3.35,1.92,72.7,6110.34
Si,41.04,7.27,0.94,4.58,1.49,71.5,6505.64

In [21]:
gb_gen = sleep_project2[["generation", "age", "sleep_duration", "sleep_efficiency", "stress_level","awakenings", "heart_rate", "daily_steps"]]
gb_gen.groupby('generation').mean().round(2)

,age,sleep_duration,sleep_efficiency,stress_level,awakenings,heart_rate,daily_steps
generation,,,,,,,
Baby Boomers,60.34,7.75,1.00,3.19,1.42,70.84,6730.38
Generacion X,47.99,7.22,0.93,4.63,1.63,71.48,6487.86
Generacion Z,21.48,7.58,0.75,3.41,1.96,72.85,6125.35
Millennials,33.53,7.24,0.90,4.68,1.42,71.81,6413.07

In [23]:
sleep_project2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   gender                  825 non-null    object
 1   age                     825 non-null    int64
 2   occupation              825 non-null    object
 3   sleep_duration          825 non-null    float64
 4   stress_level            825 non-null    float64
 5   bmi_category            825 non-null    object
 6   blood_pressure          825 non-null    object
 7   heart_rate              825 non-null    float64
 8   daily_steps             825 non-null    float64
 9   sleep_disorder          825 non-null    object
 10  sleep_efficiency        825 non-null    float64
 11  rem_sleep_percentage    825 non-null    float64
 12  deep_sleep_percentage   825 non-null    float64
 13  light_sleep_percentage  825 non-null    float64
 14  awakenings              825 non-null    float64
 15  caffeine_consumption    825 non-null    object
 16  alcohol_consumption     825 non-null    object
 17  smoking_status          825 non-null    object
 18  exercise_frequency      825 non-null    object
 19  generation              825 non-null    object
dtypes: float64(9), int64(1), object(10)
memory usage: 129.0+ KB

In [22]:
sleep_project2.columns

Index(['gender', 'age', 'occupation', 'sleep_duration', 'stress_level',
       'bmi_category', 'blood_pressure', 'heart_rate', 'daily_steps',
       'sleep_disorder', 'sleep_efficiency', 'rem_sleep_percentage',
       'deep_sleep_percentage', 'light_sleep_percentage', 'awakenings',
       'caffeine_consumption', 'alcohol_consumption', 'smoking_status',
       'exercise_frequency', 'generation'],
      dtype='object')

In [52]:
from scipy.stats import pearsonr, pointbiserialr, spearmanr

# Columnas numéricas
numerical_columns = ['sleep_efficiency', 'age', 'stress_level', 'heart_rate', 
                     'daily_steps', 'rem_sleep_percentage', 'deep_sleep_percentage', 
                     'light_sleep_percentage', 'awakenings']

# Lista para almacenar los resultados de la correlación
correlation_results_dur = []

# Calcular correlaciones con columnas numéricas
print("Correlaciones de sleep duration con columnas numéricas:")
for column in numerical_columns:
    correlation, p_value = pearsonr(sleep_project2['sleep_duration'], sleep_project2[column])
    correlation_results_dur.append({'Column': column, 'Correlation': correlation, 'P-value': p_value})

# Convertir la lista de resultados en un DataFrame
correlation_duration_numerical = pd.DataFrame(correlation_results_dur)

correlation_duration_numerical= correlation_duration_numerical.sort_values(by='Correlation', ascending=False)

# Mostrar el DataFrame de correlaciones
correlation_duration_numerical.round(4)

Correlaciones de sleep duration con columnas numéricas:

                   Column  Correlation  P-value
0        sleep_efficiency       0.2585   0.0000
7  light_sleep_percentage       0.1439   0.0000
1                     age       0.0529   0.1292
5    rem_sleep_percentage       0.0052   0.8819
4             daily_steps      -0.0312   0.3710
3              heart_rate      -0.1330   0.0001
6   deep_sleep_percentage      -0.1415   0.0000
8              awakenings      -0.1902   0.0000
2            stress_level      -0.6258   0.0000

In [53]:
from scipy.stats import pearsonr, pointbiserialr, spearmanr

# Columnas numéricas
numerical_columns = ['sleep_duration', 'age', 'stress_level', 'heart_rate', 
                     'daily_steps', 'rem_sleep_percentage', 'deep_sleep_percentage', 
                     'light_sleep_percentage', 'awakenings']

# Lista para almacenar los resultados de la correlación
correlation_results_eff = []

# Calcular correlaciones con columnas numéricas
print("Correlaciones de sleep efficiency con columnas numéricas:")
for column in numerical_columns:
    correlation, p_value = pearsonr(sleep_project2['sleep_efficiency'], sleep_project2[column])
    correlation_results_eff.append({'Column': column, 'Correlation': correlation, 'P-value': p_value})

# Convertir la lista de resultados en un DataFrame
correlation_efficiency_numerical = pd.DataFrame(correlation_results_eff)

correlation_efficiency_numerical= correlation_efficiency_numerical.sort_values(by='Correlation', ascending=False)


# Mostrar el DataFrame de correlaciones
correlation_efficiency_numerical.round(4)

Correlaciones de sleep efficiency con columnas numéricas:

                   Column  Correlation  P-value
6   deep_sleep_percentage       0.3282   0.0000
0          sleep_duration       0.2585   0.0000
1                     age       0.2488   0.0000
4             daily_steps       0.0971   0.0053
5    rem_sleep_percentage       0.0221   0.5260
2            stress_level      -0.1216   0.0005
3              heart_rate      -0.3400   0.0000
7  light_sleep_percentage      -0.3426   0.0000
8              awakenings      -0.4325   0.0000

In [32]:
from sklearn.preprocessing import LabelEncoder

# Crear una copia del DataFrame para evitar modificar el original
sleep_project2_encoded = sleep_project2.copy()

# Inicializar el codificador de etiquetas
label_encoder = LabelEncoder()

# Iterar sobre cada columna categórica y codificar las categorías
for column in categorical_columns:
    # Convertir la columna a tipo 'category' para asegurarnos de que sea tratada como categórica
    sleep_project2_encoded[column] = label_encoder.fit_transform(sleep_project2_encoded[column].astype('category'))

# Verificar el nuevo DataFrame con categorías codificadas
print(sleep_project2_encoded.head())

   gender  age  occupation  sleep_duration  stress_level  bmi_category  \
0       1   27           9             6.1           6.0             2
1       1   28           1             6.2           8.0             0
2       1   28           1             6.2           8.0             0
3       1   28           6             5.9           8.0             1
4       1   28           6             5.9           8.0             1

   blood_pressure  heart_rate  daily_steps sleep_disorder  sleep_efficiency  \
0              11        77.0       4200.0        unknown               0.8
1               9        75.0      10000.0       Insomnia               0.8
2               9        75.0      10000.0       Insomnia               0.8
3              22        85.0       3000.0    Sleep Apnea               0.4
4              22        85.0       3000.0    Sleep Apnea               0.4

   rem_sleep_percentage  deep_sleep_percentage  light_sleep_percentage  \
0                 28.57                  56.12                   15.31
1                 19.15                  63.83                   17.02
2                 26.67                  57.14                   16.19
3                 22.53                  54.53                   22.94
4                 22.53                  54.53                   22.94

   awakenings  caffeine_consumption  alcohol_consumption  smoking_status  \
0         2.0                     0                    0               1
1         3.0                     1                    0               1
2         1.0                     0                    0               0
3         1.0                     0                    0               0
4         1.0                     0                    0               0

   exercise_frequency  generation
0                   1           3
1                   1           3
2                   1           3
3                   1           3
4                   1           3

In [51]:
import pandas as pd
from scipy.stats import pointbiserialr, spearmanr

# Columnas categóricas
categorical_columns = ['gender', 'occupation', 'bmi_category', 'blood_pressure', 
                       'caffeine_consumption', 'alcohol_consumption', 'smoking_status', 
                       'exercise_frequency', 'generation']

# Lista para almacenar los resultados de la correlación
correlation_results_categorical_dur = []

# Calcular correlaciones con columnas categóricas
print("\nCorrelaciones de sleep duration con columnas categóricas:")
for column in categorical_columns:
    if len(sleep_project2_encoded[column].unique()) == 2:  # Si la columna categórica tiene solo dos categorías
        correlation, p_value = pointbiserialr(sleep_project2_encoded[column], sleep_project2_encoded['sleep_duration'])
    else:
        correlation, p_value = spearmanr(sleep_project2_encoded[column], sleep_project2_encoded['sleep_duration'])
    correlation_results_categorical_dur.append({'Column': column, 'Correlation': correlation, 'P-value': p_value})

# Convertir la lista de resultados en un DataFrame
correlation_duration_categorical = pd.DataFrame(correlation_results_categorical_dur)

correlation_duration_categorical= correlation_duration_categorical.sort_values(by='Correlation', ascending=False)


# Mostrar el DataFrame de correlaciones
correlation_duration_categorical.round(4)

Correlaciones de sleep duration con columnas categóricas:

                 Column  Correlation  P-value
5   alcohol_consumption       0.0401   0.2505
3        blood_pressure      -0.0640   0.0660
0                gender      -0.0753   0.0306
6        smoking_status      -0.0759   0.0292
8            generation      -0.0816   0.0191
1            occupation      -0.0913   0.0087
7    exercise_frequency      -0.1337   0.0001
4  caffeine_consumption      -0.1491   0.0000
2          bmi_category      -0.1793   0.0000

In [50]:
# Columnas categóricas
categorical_columns = ['gender', 'occupation', 'bmi_category', 'blood_pressure', 
                       'caffeine_consumption', 'alcohol_consumption', 'smoking_status', 
                       'exercise_frequency', 'generation']

correlation_results_categorical_eff = []

# Calcular correlaciones con columnas categóricas
print("\nCorrelaciones de sleep efficiency con columnas categóricas:")
for column in categorical_columns:
    if len(sleep_project2_encoded[column].unique()) == 2:  # Si la columna categórica tiene solo dos categorías
        correlation, p_value = pointbiserialr(sleep_project2_encoded[column], sleep_project2_encoded['sleep_efficiency'])
    else:
        correlation, p_value = spearmanr(sleep_project2_encoded[column], sleep_project2_encoded['sleep_efficiency'])
    correlation_results_categorical_eff.append({'Column': column, 'Correlation': correlation, 'P-value': p_value})

# Convertir la lista de resultados en un DataFrame
correlation_efficiency_categorical = pd.DataFrame(correlation_results_categorical_eff)

# Ordenar la tabla en función de la correlación de mayor a menor
correlation_efficiency_categorical= correlation_efficiency_categorical.sort_values(by='Correlation', ascending=False)

# Mostrar el DataFrame de correlaciones
correlation_efficiency_categorical.round(4)

Correlaciones de sleep efficiency con columnas categóricas:

                 Column  Correlation  P-value
7    exercise_frequency       0.2925   0.0000
8            generation      -0.0495   0.1559
0                gender      -0.1293   0.0002
3        blood_pressure      -0.1500   0.0000
2          bmi_category      -0.1580   0.0000
1            occupation      -0.1872   0.0000
6        smoking_status      -0.3927   0.0000
4  caffeine_consumption      -0.4120   0.0000
5   alcohol_consumption      -0.4459   0.0000